### ISSUE TITLE
[REQUEST] Have example for using with AWS Layers

### ISSUE THREAD

**Issue by danfoust** [Sparticuz/chromium#1]
### Question: how would one go about using this package with an AWS Layers setup? 

Is the process to build locally, add the zip to AWS Layers, then implement our own methods for unzipping and loading Chromium in Lambda?

---

I'm a little confused how to use your package with an AWS Layer setup.  A few years ago I setup a PDF service using the old  [alixaxel repo](https://github.com/alixaxel/chrome-aws-lambda).

I had to borrow the executable path method to unzip all the compressed binaries in the Layer.

```
async function executablePath(): Promise<string> {
    if (process.env.IS_LOCAL) {
        return path.resolve(process.cwd(), process.env.LOCAL_CHROMIUM);
    }

    if (existsSync('/tmp') && existsSync('/tmp/chromium')) {
        for (const file of readdirSync('/tmp')) {
            if (file.startsWith('core.chromium') === true) {
                unlinkSync(`/tmp/${file}`);
            }
        }

        return Promise.resolve('/tmp/chromium');
    }

    const input = process.env.CHROMIUM_EXE_DIR;
    const promises = [
        inflate(`${input}/chromium.br`),
        inflate(`${input}/swiftshader.tar.br`),
        inflate(`${input}/aws.tar.br`),
    ];

    return Promise.all(promises).then((result) => result.shift());
}
```

From your "Usage" section, it looks like that would be already handled and I could do something like this:

```
const puppeteer = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");

const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
```

which would be fantastic.  But you mention just prior that your package can only be a dev-dependency if used with AWS Layers.

```
# @sparticuz/chromium is a DEV dependency IF YOU ARE USING A LAYER, ...!
```

So, how should this package be used in an AWS/Layers setup?  Should we copy this repo's `/source` folder and use that?  What's the intended flow?

## Why would it be useful?

I essentially want this functionality in a Lambda/Layer environment:

```
const puppeteer = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");

const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
```
which handles work I would otherwise need to reimplement.

**Comment by Sparticuz** [comment]
https://github.com/Sparticuz/chromium#aws-lambda-layer

Create the layer locally (or download from the [latest test](https://github.com/Sparticuz/chromium/actions/workflows/aws.yml?query=is%3Asuccess+branch%3Amaster)) Then use that file as the layer in the Lambda Layers panel.

**Comment by danfoust** [comment]
@Sparticuz Right, I got that part.  The thing is, if I'm using a layer, `@sparticuz/chromium` needs to be a dev-dependency which won't be available in the production build, right?  So my question: is there a way to use the code below with layers, or do we need to implement the unzip logic (pretty much the [Chromium class](https://github.com/Sparticuz/chromium/blob/master/source/index.ts#L52)) ourselves?  If there's a way to use the code below with AWS Layers, that's what I was asking an example or clarity on.

```
const chromium = require("@sparticuz/chromium");

const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
```

**Comment by Sparticuz** [comment]
> `@sparticuz/chromium` needs to be a dev-dependency

That just means it won't be deployed or packaged automatically (when using `npm ci`, `npm install --production`, or `serverless deploy`, etc...). Adding it as a lambda layer 'deploys' the code so it's available. What you've got there should work.

**Comment by danfoust** [comment]
@Sparticuz I just got around to testing this out and received this error:

![image](https://user-images.githubusercontent.com/23723707/194085342-8427bb9a-cfef-4a79-bae7-7c67b463710d.png)

Looks like the path it's trying to inflate is relative.  Not sure if that's an issue with using AWS Layers.  When I did the inflate logic prior, I used an absolute path.  Here's my current setup code.  `@sparticuz/chromium` is a dev-dependency and I uploaded the `chromium.zip` as a layer.  Seems like it's failing at the `inflate` step.

```typescript
import * as path from 'path';
import * as puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

export async function launch(opts?: puppeteer.LaunchOptions): Promise<puppeteer.Browser> {
    let executablePath: string = await chromium.executablePath;

    if (!executablePath && process.env.IS_LOCAL) {
        executablePath = path.resolve(process.cwd(), process.env.LOCAL_CHROMIUM);
    }

    const options = {
        ...(opts ? opts : {}),
        args: chromium.args,
        headless: chromium.headless,
        executablePath,
        ignoreHTTPSErrors: true,
        // Fixes error undefined\temp\puppeteer_dev_chrome_profile-XXXXXX
        // https://github.com/puppeteer/puppeteer/issues/6414#issuecomment-692504551
        userDataDir: path.resolve('/tmp'),
    };

    return await puppeteer.launch(options);
}
```

**Comment by zfael** [comment]
@danfoust would you mind providing the whole file for the `getExecutablePath` function? wanna check where the `inflate` comes from

**Comment by danfoust** [comment]
> @danfoust would you mind providing the whole file for the `getExecutablePath` function? wanna check where the `inflate` comes from

```
import LambdaFS from 'lambdafs';

LambdaFS.inflate()

// Or

import { inflate } from 'lambdafs';
```

**Comment by zfael** [comment]
@danfoust thanks for sharing! yea, I have the same and still getting some weird behavior, have you faced the following when you were trying to make it work?

```
{
        "message": "Failed to launch the browser process!\n/tmp/chromium: /tmp/chromium: cannot execute binary file\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
        "details": {}
    }
```

**Comment by zfael** [comment]
ok cool -- turns out that I was using lambda arch `arm64` and that's not compatible with chromium, changing that to `x86_64` worked!

**Comment by roberttolton** [comment]
Hi all, thanks for everyone's work on this package and their notes in this issue.

However, I cannot get this to work even though it seems like it should be straightforward?

- I've published the layer, I've got it referenced in my `template.yaml` file for the function.
- I only have `esbuild` and `lambdafs` in my dependencies
- `@sparticuz/chromium` and `puppeteer-core` are amongst my dev-dependencies

I am importing things as follows:

```
import * as puppeteer from 'puppeteer-core'
import chromium from '@sparticuz/chromium'
import { getChromiumExecutablePath } from '../helpers'
```

`getChromiumExecutablePath` is the function from @danfoust above, with some Typescript fixes.

My whole file is:

```
import { ShopifyOrderShareImageEvent } from '../types'
import { APIGatewayProxyResult } from 'aws-lambda'
import * as path from 'path'
import * as puppeteer from 'puppeteer-core'
import chromium from '@sparticuz/chromium'
import { getChromiumExecutablePath } from '../helpers'

/**
 *
 * Event doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format
 * @param {Object} event - API Gateway Lambda Proxy Input Format
 *
 * Return doc: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
 * @returns {Object} object - API Gateway Lambda Proxy Output Format
 *
 */

exports.handle = async (event: ShopifyOrderShareImageEvent): Promise<APIGatewayProxyResult> => {

    if (event.warming) {

        return {
            statusCode: 200,
            body: JSON.stringify({
                message: 'warming',
            }),
        }

    }

    let executablePath: string = await getChromiumExecutablePath()

    const browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath,
        headless: chromium.headless,
        ignoreHTTPSErrors: true,
        userDataDir: path.resolve('/tmp'),
    })

    const page = await browser.newPage()

    await page.setViewport({ width: 1920, height: 1080 })

    // @todo

    let response: APIGatewayProxyResult

    try {

        response = {
            statusCode: 200,
            body: JSON.stringify({
                message: 'test',
            }),
        }

    } catch (err: unknown) {
        console.error(err)
        response = {
            statusCode: 500,
            body: JSON.stringify({
                message: err instanceof Error ? err.message : 'Unknown Error',
            }),
        }
    }

    return response
}
```

However, no matter what I seem to try, I just get this error that it can't find the module:

```
2022-11-15T15:45:18.711Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'puppeteer-core'\nRequire stack:\n- /var/task/handlers.js\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'puppeteer-core'","Require stack:","- /var/task/handlers.js","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)","    at async start (file:///var/runtime/index.mjs:1200:23)","    at async file:///var/runtime/index.mjs:1206:1"]}
```

Any clues?

**Comment by danfoust** [comment]
@roberttolton 

puppeteer-core needs to be a dependency, not devDependency.

**Comment by roberttolton** [comment]
@danfoust D'oh, thanks! You're absolutely right about that.

However, changing that and running a rebuild and re-trying to invoke the function locally (`sam invoke`) still gave me the error. Have you ever tried it with invoking locally?

**Comment by danfoust** [comment]
You'll need to have chromium installed locally.  I have `puppeteer` as a devDependency, which comes with a chromium executable and easily allows you to have puppeteer and puppeteer-core in sync. 

Then I have an env variable which I key off of to return the path to the exe in `node_modules/puppeteer`.

**Comment by roberttolton** [comment]
@danfoust Thanks. As I understand it, the `sam invoke` will run the Lambda command fully locally, replicating as if it were in the cloud, so I shouldn't need anything else other than what's already defined for the function?

I also just tried to run the function in the cloud now, and I'm still getting the `Cannot find module 'puppeteer-core'` error. So I'm going to try and brute-debug this with looking through the filesystem in `/opt` and see if the layer is correct? It should be OK, I used the ZIP inside the ZIP provided by the CI workflow which was a common issue I saw here.

**Comment by roberttolton** [comment]
@danfoust Thanks, I shouldn't need `chromium` installed locally as using the `invoke` function is like running the Lambda, but virtually on the local setup, so it should be a 'mirror'.

But I realised that, in my misunderstanding about the `puppeteer-core` needing to be a dependency, I had excluded it in the `esbuild` config. With that removed, it seems to be working (now I just have an issue where my environment variables aren't being picked-up from the `--env-vars` flag.. it's always something!)
