### ISSUE TITLE
[BUG] Accessible/Tagged PDFs not generated when running on Lambda

### ISSUE THREAD

**Issue by dom-jones-1** [Sparticuz/chromium#113]
## Environment

- `chromium` Version: HeadlessChrome/112.0.5614.0
- `puppeteer` / `puppeteer-core` Version: 19.8.0
- Node.js Version: 18.x
- Lambda / GCF Runtime: `nodejs18.x`

## Expected Behavior

This chromium version should produce tagged PDFs by default.

## Current Behavior

When running the code locally, tagged PDFs are created, but when deployed on Lambda it just creates a regular PDF with no accessibility attributes.

## Steps to Reproduce

Generate a PDF and verify if it has accessibility attributes - I use VoiceOver to check if `h1` tags are announced correctly.

## Possible Solution

Really just looking for advice on what the issue might be - what differences would there be running this locally vs in Lambda?

**Comment by dom-jones-1** [comment]
My testing so far indicates the problem is caused by the included Chromium binary. When I use the default executablePath and get the default browser, it does not generate accessibility tags - if I install chromium through yum and point the executablePath there it works fine.

Is there supposed to be any difference between the two?

**Comment by jmarotta-es** [comment]
@dom-jones-1 The chromium binary is compiled with ansible as described [here](https://github.com/Sparticuz/chromium/blob/master/_/ansible/README.md). It's likely coming from the [settings used to compile chromium](https://github.com/Sparticuz/chromium/blob/74283507ac24bf17bf306bc4765b94bb48a225b3/_/ansible/plays/chromium.yml#L245-L274).

**Comment by Sparticuz** [comment]
I believe it's probably because we are using the headless_shell example code. Likely this is the reason for all the bugs.

**Comment by jmarotta-es** [comment]
I generated an accessible PDF by changing **_/ansible/plays/chromium.yml**. In the `Creating Headless Chromium Configuration` play I removed 
```
enable_basic_print_dialog = false
```
and added the following
```
enable_basic_printing = true
enable_pdf = true
enable_tagged_pdf = true
```

NOTE: This will dramatically increase the time required to generate a PDF.

**Comment by OzanBarsal** [comment]
> I generated an accessible PDF by changing **_/ansible/plays/chromium.yml**. In the `Creating Headless Chromium Configuration` play I removed
> 
> ```
> enable_basic_print_dialog = false
> ```
> 
> and added the following
> 
> ```
> enable_basic_printing = true
> enable_pdf = true
> enable_tagged_pdf = true
> ```
> 
> NOTE: This will increase the time required to generate a PDF.

Sorry for crowding the issue but would you mind sharing the chromium binary you've created? I've been getting build errors with my attempts :(
