### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JaredAAT** [Sparticuz/chromium#114]
## Environment

- `chromium` Version: ^114.0.0
- `puppeteer` / `puppeteer-core` Version: ^20.7.1
- Node.js Version: 18.x
- Lambda: `nodejs18.x`

## Expected Behavior

Closes the browser in a timely manner

## Current Behavior

Closes the browser in a timeless manner 😄 It seems that on AWS Lambda, when I run an `await browser.close()` it takes about 3 minutes to close the browser.  I'm not sure if this is expected.

Here I am logging out a message before I close:

| Date Time| uuid| log type| log
|------|-----|----|------
|2023-06-16T10:17:10.365Z |	1828d1fd-29a9-436b-97d9-7054c9e3abdf|	INFO|	closing browser

and here I log out after the browser has closed:
| Date Time| uuid| log type| log
|------|-----|----|------
|2023-06-16T10:20:10.472Z|	1828d1fd-29a9-436b-97d9-7054c9e3abdf|	INFO|	closed

As you can see, it takes about 3 minutes to close.

## Steps to Reproduce

```js
const chromium = require("@sparticuz/chromium");
const puppeteer = require("puppeteer-core");

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
   let browser;
  if (process.env.IS_OFFLINE) {
        console.info("RUNNING OFFLINE. USING PCR TO GET CHROMIUM");
        const PCR = require("puppeteer-chromium-resolver");
        const stats = await PCR({});
        puppeteerOptions.executablePath = stats.executablePath;
      } else {
        puppeteerOptions.executablePath = await chromium.executablePath();
      }
     browser = await puppeteer.launch(puppeteerOptions);
     const page = await browser.newPage();
     await page.setContent(someContent);
     await page.emulateMediaType("screen");
     const pdf = await page.pdf({
        margin: {
          top: "1cm",
          right: "1cm",
          bottom: "1cm",
          left: "1cm",
        },
        printBackground: true,
        width: "700px",
        height: "1000px",
      });
     browser.disconnect();
     await browser.close();
  } catch (error) {
    return callback(error);
  } 

  return callback(null, result);
};
```

**Comment by Sparticuz** [comment]
Dupe #85
