### ISSUE TITLE
[BUG] Investigate Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1045629)

### ISSUE THREAD

**Issue by pratiksyngenta** [Sparticuz/chromium#12]
## Environment
* `chromium` Version: "@sparticuz/chromium": "^106.0.2",
* `puppeteer` / `puppeteer-core` Version: ^18.0.5
* Node.js Version:  v16.13.2
* Lambda / GCF Runtime: 

## Current Behavior

Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1045629)

**Comment by lubuzzo** [comment]
Hey, @pratiksyngenta.

I'd like to recommend to you double check if you have specified the "executablePath" property in the launch of the Puppeteer, as you can see [here](https://github.com/Sparticuz/chromium/blob/master/README.md?plain=1#L52).

In case this not solve the problem, you can try double check the Chromium version supported by Puppeteer [here](https://pptr.dev/chromium-support/).

**Comment by Sparticuz** [comment]
It might also be that the `headless` function is returning false. The functionality was altered in 108.0.1.

**Comment by Sparticuz** [comment]
Try again using 108.0.1 or higher
