### ISSUE TITLE
[REQUEST/BUG] executablePath and Windows

### ISSUE THREAD

**Issue by b5414** [Sparticuz/chromium#13]
## What would you like to have implemented?

When you use the playwright with this chrome package - an error occurs on windows

According to my tests it is related to chrome path: `browser.executablePath = await chromium.executablePath;`

## Why would it be useful?

No useless os checks and no error: `browserType.launch: Failed to launch: Error: spawn F:\temp\chromium ENOENT`

---

It was implemented in `@sparticuz/chrome-aws-lambda`, but skipped in `@sparticuz/chromium`

by that, I meant you could just:
```js
browser.executablePath = (await chromium.executablePath) || '';
const browser = await playwright.launch(browser);
```

So for windows it was: '' = _use installed chrome_, but for aws: 'some/chrome/path/'

**Comment by Sparticuz** [comment]
This binary will not work in Windows. It's build for linux only. I'm not even aware of any serverless platforms that run on windows. If you are running your own platform, you should be able to just install chromium using the normal windows install binary directly from chromium.

That said, at this point, I am not planning to support windows.

**Comment by b5414** [comment]
@Sparticuz re:

It was implemented in `@sparticuz/chrome-aws-lambda`, but skipped in `@sparticuz/chromium`



by that, I meant you could just:
```js
browser.executablePath = (await chromium.executablePath) || '';
const browser = await playwright.launch(browser);
```

So for windows it was: '' = _use installed chrome_, but for aws: 'some/chrome/path/'

**Comment by b5414** [comment]
I don't need "support windows plslpslpspl" or something like this

---

Once again:

### input data:

I have installed chrome on windows, it works when i put: `browser.executablePath = '';`

On aws I should put `browser.executablePath = await chromium.executablePath;` and it's working well

### the case with `@sparticuz/chrome-aws-lambda`

I do: `browser.executablePath = (await chromium.executablePath) || '';`
I recieve:
- Win: `''`;
- Aws: `<path>`;

### the case with `@sparticuz/chromium`

I do: `browser.executablePath = (await chromium.executablePath) || '';` // same as above
I recieve:
- Win: `<something_maybe_path>`;
- Aws: `<path>`;

**Comment by b5414** [comment]
@Sparticuz

**Comment by jeanbmar** [comment]
Projects don't use it on Windows in production but it could be useful to serve Windows binaries for development purpose
