### ISSUE TITLE
[BUG] Error: The input directory "/app/.webpack/s ervice/bin" does not exist.  At Function.executablePath

### ISSUE THREAD

**Issue by antonioOrtiz** [Sparticuz/chromium#138]
I followed the setup [here](https://www.npmjs.com/package/@sparticuz/chromium):

[puppeteer ships with a prefered version of chromium](https://pptr.dev/faq/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy). In order to figure out what version of @sparticuz/chromium you will need, please visit [Puppeteer's Chromium Support page](https://pptr.dev/chromium-support).

> For example, as of today, the latest version of puppeteer is 18.0.5. The latest version of chromium stated on puppeteer's support page is 106.0.5249.0. So you need to install @sparticuz/chromium@106.

## Environment

- `chromium` Version: `@sparticuz/chromium": "^115.0.0`
- `puppeteer` / `puppeteer-core` Version: `"puppeteer": "^21.1.0",` and `"puppeteer-core": "^10.4.0",`
- Node.js Version:  `v18.16.0`
- Lambda / GCF Runtime:  I'm just using this locally

## Expected Behavior

A PDF should have been genreated from a **.ejs** template
## Current Behavior
>  Error: The input directory "/mnt/d/Repos/document-engine/.webpack/s
ervice/bin" does not exist.
    at Function.executablePath (/mnt/d/Repos/document-engine/.webpack/service/src/webpack:/document-engine-service/node_modules/@sparticuz/chromium/bu
ild/index.js:225:1)

This is the service being used in my app:

```
async generatePdfBuffer(dsDocGeneratePDFRequestModel: DSDocGeneratePDFRequestModel): Promise < Buffer > {
    let browser: any;
    let chromeTmpDataDir: string = null;
    try {
        const ejsTemplate: string =
            dsDocGeneratePDFRequestModel.templateText ||
            (await this.messageService.getEmailTemplate(dsDocGeneratePDFRequestModel.cloudTemplateBucket, dsDocGeneratePDFRequestModel.cloudTemplatePath));

        const content: string = await this.dsEmailTemplateService.renderHtml(ejsTemplate, dsDocGeneratePDFRequestModel.data);

        // Optional: If you'd like to use the legacy headless mode. "new" is the default.
        chromium.setHeadlessMode = true;

        // Optional: If you'd like to disable webgl, true is the default.
        chromium.setGraphicsMode = false;

        browser = await puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath(),
            headless: true
        });
        const chromeSpawnArgs: string[] = browser.process().spawnargs;
        chromeSpawnArgs.forEach((eachChromeSpawnArgs) => {
            if (eachChromeSpawnArgs.indexOf('--user-data-dir=') === 0) {
                chromeTmpDataDir = eachChromeSpawnArgs.replace('--user-data-dir=', '');
            }
        });
        const page: any = await browser.newPage();
        await page.setContent(content);

        const buffer: Buffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: {
                left: '0px',
                top: '0px',
                right: '0px',
                bottom: '0px'
            }
        });

        return buffer;
    } catch (error) {
        this.logService.error(error);
        throw Error;
    } finally {
        await browser?.close();
        if (chromeTmpDataDir !== null) {
            fs?.removeSync(chromeTmpDataDir);
        }
    }
}
}
```

So what am I doing wrong which prevents a PDF from being created?

**Comment by Sparticuz** [comment]
If you are using webpack, you need to set it as an external https://github.com/Sparticuz/chromium/issues/24#issuecomment-1343196897

**Comment by antonioOrtiz** [comment]
This led me to a solution, i.e [webpack externals](https://webpack.js.org/configuration/externals/) Thank you!
