### ISSUE TITLE
 [Question] MapboxGL return empty screenshot and PDF

### ISSUE THREAD

**Issue by serhii-baksheiev** [Sparticuz/chromium#141]
what settings should I use to make mapboxgl display the map? I tested it locally with a puppeteer and it works fine for me. But after deploying lambda to aws, I ran into a problem that I needed to add a layer. My lambda was big enough, so I used the -min package and loaded the layer into S3. Everything except the map is displayed normally. I would appreciate any help

Settings I have

`
   const html = createHtml(script);  // some simpe function with creating HTML file
    const browser = await puppeteer.launch({
      args: [...chromium.args, '--enable-webgl', '--use-angle'],
      executablePath: await chromium.executablePath(
        'path to s3'
      ),
    });
    const page = await browser.newPage();

    await page.setViewport({ width: 1280, height: 720 });
    await page.setContent(html, { waitUntil: 'networkidle0' });
`

without these two flags '--enable-webgl', '--use-angle' I receive timeout. I also checked HTML and in a browser code works good

versions I use

"@sparticuz/chromium-min": "116.0.0",
"puppeteer-core": "19.6.3",

**Comment by Sparticuz** [comment]
The only combination of flags that I've been able to get chromium to launch with on Lambda is `"--use-gl=angle", "--use-angle=swiftshader"`.
