### ISSUE TITLE
[REQUEST] Please, make it work with Nextjs 13 

### ISSUE THREAD

**Issue by ambrosil** [Sparticuz/chromium#147]
## What would you like to have implemented?

It would be awesome if you could add support for Next.js 13.
What happens right now is that the chromium.br file just disappear during the build with webpack 5 (i think cuz *br files are not handled by the webpack config, but i'm not completely sure), so i get this error when launching puppeteer server side in a Next.js app:

```
Error: The input directory "/var/task/.next/server/bin" does not exist.
    at Chromium.executablePath (/var/task/.next/server/chunks/867.js:45085:19)
    at printPdf (/var/task/.next/server/app/api/pdf/route.js:772:47)
    at GET (/var/task/.next/server/app/api/pdf/route.js:718:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/.next/server/chunks/778.js:6189:37
```

Can you help me, please ?

**Comment by Sparticuz** [comment]
@ambrosil Must be listed as a webpack external

**Comment by ambrosil** [comment]
ok, you mean like this ?

`config.externals.push('@sparticuz/chromium')`

**Comment by Sparticuz** [comment]
@ambrosil No idea, I don't use Web pack, but there is a link to a thread on the main page with more information.

**Comment by ambrosil** [comment]
ok i'll try., thanks for the support 👍

**Comment by LuanCKRG** [comment]
I've been having the same issue for weeks now, wondering if you got any links or progress?

**Comment by Sparticuz** [comment]
https://github.com/Sparticuz/chromium/issues/24#issuecomment-1343196897

**Comment by Sparticuz** [comment]
That code looks wrong. The externals documentation says to do something like
```
module.exports = {
  //...
  externals: {
    jquery: 'jQuery',
  },
};
```

**Comment by Sparticuz** [comment]
You may have to use the `@sparticuz/chromium-min` package and host the binary separately from your app

**Comment by Sparticuz** [comment]
I do understand wanting to run your code together, but it's my advice that you decouple any chromium interactions from your users and maybe just run this separate. SQS with vanilla Lambda. All these build systems do things differently. That said, if you do figure it out, I'd be happy to add some info in the readme, or add examples.

**Comment by Sparticuz** [comment]
> The 60 second timeout was being caused by an unnecessary `await browser.close();` at end end of my code block.
> 

I've heard that disabling the graphics stack will fix this bug

**Comment by masterbater** [comment]
https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages

**Comment by foufrix** [comment]
> As @masterbater said, the config should be:
> 
> ```js
> const nextConfig = {
>   experimental: {
>     serverComponentsExternalPackages: [
>       'puppeteer-core',
>       '@sparticuz/chromium'
>     ]
>   }
> }
> ```

Does this work when trying to run puppeteer using Vercel cloud functions?

**Comment by mordechaim** [comment]
> Does this work when trying to run puppeteer using Vercel cloud functions?

Yes, but I had to use chromium-min instead since it reached the 50MB limit. See [this article](https://www.stefanjudis.com/blog/how-to-use-headless-chrome-in-serverless-functions/) on how to do it.

Puppeteer also took quite long to load my heavy page, which reached the max 10 second execution time of Vercel cloud, so I'm now using Vercel Pro with increased [`maxDuration`](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#maxduration) route segment config.

**Comment by nayanbari** [comment]
> > As @masterbater said, the config should be:
> > ```js
> > const nextConfig = {
> >   experimental: {
> >     serverComponentsExternalPackages: [
> >       'puppeteer-core',
> >       '@sparticuz/chromium'
> >     ]
> >   }
> > }
> > ```
> 
> Does this work when trying to run puppeteer using Vercel cloud functions?

Thanks @foufrix above solution worked for me.
