### ISSUE TITLE
[BUG] Headless new

### ISSUE THREAD

**Issue by b5414** [Sparticuz/chromium#151]
`...chromium.args,` always brings `"--headless='new'",` to args array

**Comment by Sparticuz** [comment]
https://github.com/Sparticuz/chromium#usage

**Comment by b5414** [comment]
Why do we need these? One option is not enough? 

- `chromium.setHeadlessMode`
- `chromium.launch({args: ['--headless']});`
- `chromium.launch({headless});` _true one_

**Comment by Sparticuz** [comment]
setHeadlessMode will set the type of headless mode, adding the correct args that get passed.

Your second option will not pass [all the other flags that are set by this package](https://github.com/Sparticuz/chromium/blob/master/source/index.ts#L154-L233), most likely preventing Chromium from running on Lambda.

The third option is the Puppeteer headless flag, not related to how chromium launches.
