### ISSUE TITLE
Going beyond Puppeteer 19?

### ISSUE THREAD

**Issue by jaimeiniesta** [Sparticuz/chromium#160]
Hi! I see that in https://pptr.dev/chromium-support , version 19 is the last using Chromium, and from version 20 they use "Chromium For Testing" instead.

Are there plans to support this?

**Comment by Sparticuz** [comment]
A few reasons to say not right now.
- It's huge, like over 250 megs when I last checked, tons of dependecies, not well suited for serverless environments (at this point)
- AWS Lambda (the primary serverless environment that this package supports) is quite old, it doesn't support the newer glibc that is required to run full chromium or chrome for testing, or even the new headless mode. I probably need to put something in the readme about these issues.

**Comment by jaimeiniesta** [comment]
Sounds fine to me, thanks for the detailed explanation!

In fact I would be happy with upgrading up to puppeteer 19, which is the first one where I've seen `fullPage: false` is respected when taking a screenshot, it works locally but crashes in Vercel. Oh well, I'm still investigating.

Thanks!

**Comment by jaimeiniesta** [comment]
Related issue: https://github.com/puppeteer/puppeteer/issues/10327
