### ISSUE TITLE
[BUG] fullPage: false not respected when taking a screenshot

### ISSUE THREAD

**Issue by jaimeiniesta** [Sparticuz/chromium#162]
Hi, I'm not sure if this is a puppeteer or chromium bug, because it's currently failing with puppeteer 10 to 18 + chromium, but I have a script using puppeteer 10 + chrome-aws-lambda where it works correctly.

## Environment

- `chromium` Version: 117
- `puppeteer` / `puppeteer-core` Version: 18.2.1
- Node.js Version: 18.x
- Lambda / GCF Runtime:  nodejs18.x

## Expected Behavior

Taking a screenshot should be non-full-page by default. Specifying `fullPage: false` should also force this.

## Current Behavior

The screenshot taken is always full page, regardless of using the default or specifying `fullPage: false`.

This fails both in development and in Vercel, it's always full page.

## Steps to Reproduce

This repo contains a full example that you can try locally or deploy to Vercel.

The line where we take the screenshot is this one:

https://github.com/jaimeiniesta/screenshot-nextjs/blob/master/pages/api/screenshot.js#L53

## Possible Solution

I've seen that upgrading to Puppeteer 19 fixes that, as per this PR https://github.com/jaimeiniesta/screenshot-nextjs/pull/10

But then it works in development, but times out in Vercel. So I'd prefer to stay in a lower puppeteer version if I can get the non-full page setting to work as expected.

**Comment by Sparticuz** [comment]
iirc, there was a puppeteer issue that addressed this?
