### ISSUE TITLE
[BUG] Locally | ` input ??= (0, node_path_1.join)(__dirname, "..", "bin")`

### ISSUE THREAD

**Issue by navalta3030** [Sparticuz/chromium#163]
## Environment

- `chromium` Version: 1080
- `playwright` / `playwright-core` Version: 1.38.0
- Node.js Version: 16
- Lambda / GCF Runtime: nodejs16 (macbook)

## Expected Behavior

Local lambda invoke should had proceed importing the package.

## Current Behavior

Getting error
```
node_modules/@sparticuz/chromium/build/index.js:220
          input ??= (0, node_path_1.join)(__dirname, "..", "bin");
```

## Steps to Reproduce

```js
import { chromium } from 'playwright-core'
import awsChromium from '@sparticuz/chromium'

exports.handler = async (event, context, callback) => {

  try {
    const browser = await chromium.launch({
      args: awsChromium.args,
      executablePath: await awsChromium.executablePath(),
      headless: awsChromium.headless
    })
  } catch (error) {
    return callback(error);
  } finally {
  }
};
```

**Comment by navalta3030** [comment]
I've already installed my chromium in `~/Library/Caches/ms-playwright/......` and verified, however it seems that this package is looking from the node_modules bin?

**Comment by Sparticuz** [comment]
https://github.com/Sparticuz/chromium?tab=readme-ov-file#running-locally--headlessheadful-mode

**Comment by navalta3030** [comment]
Thanks @Sparticuz - I've tried that one and it didn't work out. I don't have an M1 chip and I also have commented out the browser launch part and it still is giving an error. I think it's on the package import where it's failing. 

```
import { chromium } from 'playwright-core'
import awsChromium from '@sparticuz/chromium'

// const browser = await chromium.launch({
    //   args: process.env.IS_LOCAL ? chromium.defaultArgs() : awsChromium.args,
    //   executablePath: process.env.IS_LOCAL
    //     ? '/tmp/localChromium/chromium/mac-1199591/chrome-mac/chrome'
    //     : await awsChromium.executablePath(),
    //   headless: process.env.IS_LOCAL ? false : awsChromium.headless
    // })
```

**Comment by navalta3030** [comment]
```$ DEVELOPMENT=local IS_LOCAL=true AWS_PROFILE=rpts serverless invoke local --function reportExport --path /Users/mark/Desktop/meltwater/repository/rpt-custom-oven/event-presentation.json
✖ /Users/mark/Desktop/meltwater/repository/rpt-custom-oven/node_modules/@sparticuz/chromium/build/index.js:220
          input ??= (0, node_path_1.join)(__dirname, "..", "bin");
                 ^
  
  SyntaxError: Invalid or unexpected token
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Environment: darwin, node 16.20.2, framework 3.35.2 (local), plugin 7.0.3, SDK 4.4.0
Credentials: Local, "rpts" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

```

**Comment by Sparticuz** [comment]
What I mean by that, is that if you are launching locally, you shouldn't be using this package. So instead of using `awsChromium.executablePath()`, you'll want to use your local path `~/Library/Caches/ms-playwright/......` (I would have absolute path instead of relative though).

**Comment by Sparticuz** [comment]
nullish coalescing assignment works on node 15+. https://node.green/#ES2021-features-Logical-Assignment-----basic-support

node: prefixing is also supported in node 14.18.0+

If you are testing inside of serverless invoke, you should use the package version, not the locally installed version of chromium though. It sounds like there is maybe some code packaging going on? If so, you'll need to specify that this package is left alone, using something like webpack externals.

**Comment by navalta3030** [comment]
That's a good point. 

This is what we currently have in externals:
```
bundle:
    externals:
      - '@sparticuz/chromium'
      - 'node_modules/@sparticuz/chromium'
      - 'playwright-core'
      - '@middy/core'
      - '@middy/http-json-body-parser'
      - 'uuid'
    packager: 'yarn'
    linting: false
```

**Comment by navalta3030** [comment]
I've downgraded to 109.1 where `node:fs` is not present. It doesn't work well for me on a package where it performs `node:fs`. 

I was already using serverless runtime of nodejs16.x and also tried nodejs18.x and didn't work out.

**Comment by kennis-amazon** [comment]
Try setting the environment variable `NODE_VERSION=18` (or other version) when you run your program.

**Comment by navalta3030** [comment]
@kennis-amazon that doesn't seem to do it. It looks like `@sparticuz/chromium` is running it's own node version.

**Comment by Sparticuz** [comment]
This is just a package, it's working fine on [Node 16](https://github.com/Sparticuz/chromium/actions/runs/6238988315/job/16935980297#step:8:1) and [18](https://github.com/Sparticuz/chromium/actions/runs/6238988315/job/16935980476#step:8:1), which get tested on every commit. If something is not working, it's generally the environment it's being run in.

**Comment by navalta3030** [comment]
Any other dependencies you think I should try to update? the environment says it's 18 and framework is also updated.

```
Environment: darwin, node 18.18.0, framework 3.35.2 (local), plugin 7.0.5, SDK 4.4.0
Credentials: Local, "rpts" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```

**Comment by navalta3030** [comment]
confirmed this is more on the serverless than the package. Was able to reproduce it without sparticuz.

**Comment by navalta3030** [comment]
Looks like the cause is we don't use type module in our package json
