### ISSUE TITLE
Possibility of support for 1:N?

### ISSUE THREAD

**Issue by GabriellArthur** [Sparticuz/chromium#176]
## Environment

- `chromium` Version: "118.0.0"
- `puppeteer-core` Version: "21.5.0",
- Node.js Version:  18.x
- Lambda: `nodejs18.x` 

## Expected Behavior

For each processing of a lambda to use `puppeteer` it needs to execute `launch` and at the end execute `close` of the browser, this way every time it executes this lambda, it will execute launch the same amount of time, a complexity of 1:1 but if this browser has an instance and always reuses it, it would have a complexity of 1:N, the question is does it have an implementation or any documentation regarding support?

## Current Behavior

just processing one page, using a 1:1 lambda complexity

## Code

```js
      const browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin'),
        headless: chromium.headless,
        ignoreHTTPSErrors: true,
      });

      this.logger.debug(`browser: ${browser}`);

      const page = await browser.newPage();

      await page.setContent(html);

      await page.emulateMediaType('screen');

      const pdf = await page.pdf({
        printBackground: true,
        format: 'A4',
      });

      this.logger.debug(`pdf: ${pdf}`);

      await browser.close();
      return pdf;
 ```

## Possible Solution

support for 1:N?

**Comment by Sparticuz** [comment]
Some tips: Don't run chromium.executablePath inside your loop. Don't run puppeteer.launch inside your loop. Put them both outside of your main loop and it will keep them open for warm starts.

**Comment by themattrobinson** [comment]
Check into this- it looks like it may have a great solution for multi-run
Lambdas.


- Matt



*Matthew Robinson,* Co-founder, Engineering
*TALON*healthtech.com <https://talonhealthtech.com/>
