### ISSUE TITLE
Issue with Scripts Not Loading in AWS Lambda using Chromium + Playwright-Core, but Working Locally

### ISSUE THREAD

**Issue by vexelgray** [Sparticuz/chromium#189]
Hello,

I'm facing a peculiar issue while using Chromium in an AWS Lambda environment for web scraping. The website in question is https://deporsite.centroinsulardedeportesgc.com/reserva-clases. When I try to load this website in the Lambda environment, certain scripts on the page don't seem to load correctly, preventing a critical table on the page from rendering.

**Description of the Problem:**

The specific problem arises when navigating to https://deporsite.centroinsulardedeportesgc.com/reserva-clases using Chromium in AWS Lambda. The expected behavior is to see the page fully loaded with a particular table displayed. However, it seems the scripts responsible for this table's rendering aren't executing as they should, leaving the page in a perpetual "loading" state, and the table never appears.

![screenshot-1700984973380](https://github.com/Sparticuz/chromium/assets/1415826/5fb63370-a682-4287-8cb1-16f3ced508f3)

**Local Environment vs. AWS Lambda:**

Interestingly, when I run the same script locally using Playwright with Chromium, everything loads perfectly without any issues. The page and the table render as expected. This issue seems to be specific to the AWS Lambda environment.

**Steps to Reproduce:**

Set up Chromium in an AWS Lambda environment.
Navigate to https://deporsite.centroinsulardedeportesgc.com/reserva-clases.
Observe the page's loading behavior.

**Expected Behavior:**
The page should load completely, with the table and all other elements rendered correctly (as it does in the local Playwright environment).

<img width="1257" alt="Captura de pantalla 2023-11-26 a las 11 42 12" src="https://github.com/Sparticuz/chromium/assets/1415826/c0e6d7dd-fc04-46aa-9db5-230aff3fd285">

**Actual Behavior in AWS Lambda:**

The page stays in a loading state indefinitely, and the table does not render at all.

Environment:

Chromium version: 119.0
Playwright version: 1.39.0
Local environment OS: MacOS 14.1.1 (23B81)
Additional tools/libraries used: "aws-sdk": "^2.1502.0"

Code:

<img width="680" alt="Captura de pantalla 2023-11-26 a las 11 49 20" src="https://github.com/Sparticuz/chromium/assets/1415826/e9fdd906-16f1-48fd-8fbc-242f054cf8cc">

Thank you in advance for your assistance and expertise.

**Comment by joergbaier** [comment]
Could be a few things

You may need to pass `page.goto(url, { waitUntil: foo })`
https://pptr.dev/api/puppeteer.puppeteerlifecycleevent

You may need to adjust the page size

You may need to increase the lambda's cpu/mem

**Comment by joergbaier** [comment]
Maybe look into the args you can add before your `const browser = ...` call?

chromium.args.push("--disable-web-security");

**Comment by vexelgray** [comment]
I appreciate your suggestions regarding the use of additional arguments with the browser instance. I've experimented with both:

chromium.args.push("--disable-web-security");
chromium.setGraphicsMode = false; chromium.setHeadlessMode = true;

Unfortunately, neither approach resolved the issue. I continue to encounter a 404 error when attempting to load resources from https://resources.deporsite.net/ using these methods.

Additionally, I've tried using both Puppeteer and Selenium to access the site, but the outcome remains the same – a persistent 404 error. This leads me to believe that there's something specific about the website https://resources.deporsite.net/ that consistently triggers a 404 response, regardless of the browser automation tool or configuration used.

If anyone has insights or additional suggestions on how to address this, they would be greatly appreciated.

**Comment by Sparticuz** [comment]
That site also gives me a 404 just browsing in a web browser. It looks like the site might only be accessible to you locally.

**Comment by vexelgray** [comment]
Thank you for your input. It's interesting to note that you're receiving a 404 error when browsing the site. 

I can confirm that I am able to access the following resources through a web browser without encountering any 404 errors:

https://resources.deporsite.net/css/bootstrap/3.3.4/src/bootstrap.min.css
https://resources.deporsite.net/css/jquery-ui/1.11.4/jquery-ui.css
https://resources.deporsite.net/js/jquery-ui/1.11.4/jquery-ui.js
https://resources.deporsite.net/js/jquery-widget/1.10.3/jquery.widget.min.js
https://resources.deporsite.net/css/material-icons/0.0.1/material-icons.css
https://resources.deporsite.net/js/material-bootstrap/0.0.1/ripples.js
https://resources.deporsite.net/js/jquery/1.12.3/jquery.min.js
https://resources.deporsite.net/js/material-bootstrap/0.0.1/material.js
https://resources.deporsite.net/js/bootstrap/3.0.3/bootstrap.min.js
https://resources.deporsite.net//fonts/roboto/Roboto-Light.woff2
https://resources.deporsite.net//fonts/roboto/Roboto-Medium.woff2
https://resources.deporsite.net//fonts/roboto/Roboto-Regular.woff2
https://resources.deporsite.net/fonts/robotocondensed/RobotoCondensed-Regular.ttf
https://resources.deporsite.net//fonts/roboto/Roboto-Light.woff
https://resources.deporsite.net//fonts/roboto/Roboto-Medium.woff
https://resources.deporsite.net//fonts/roboto/Roboto-Regular.woff
https://resources.deporsite.net//fonts/roboto/Roboto-Medium.ttf
https://resources.deporsite.net//fonts/roboto/Roboto-Light.ttf
https://resources.deporsite.net//fonts/roboto/Roboto-Regular.ttf

Continuing with the issue, I would like to ask if you are able to view the contents of the .js and .css files that I am able to access. Here are some examples:

https://resources.deporsite.net/css/bootstrap/3.3.4/src/bootstrap.min.css
https://resources.deporsite.net/js/jquery/1.12.3/jquery.min.js
https://resources.deporsite.net/js/material-bootstrap/0.0.1/material.js

In my case, I can view these files in the browser without any problems. This could help determine if the issue is specific to certain types of files or if it's a more general accessibility problem with the site.

Any further insights or suggestions would be greatly appreciated.

**Comment by Sparticuz** [comment]
All those links give 404

![Screenshot_20231203-064205.png](https://github.com/Sparticuz/chromium/assets/161913/1158c401-91ec-4ef2-ba24-363b742fa3da)

It looks like you might have some geo or IP blocking on the site.

**Comment by vexelgray** [comment]
I've been wrestling with this issue for days and it's really frustrating. I've tried setting the geolocation to Spain, but I'm still facing the same problem. If anyone has insights into why this is happening, I'd greatly appreciate it. I'm pretty stuck at the moment.

[
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/css/bootstrap/3.3.4/src/bootstrap.min.css - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633096
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/js/jquery-widget/1.10.3/jquery.widget.min.js - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633100
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/css/jquery-ui/1.11.4/jquery-ui.css - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633102
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/js/material-bootstrap/0.0.1/ripples.js - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633103
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/js/jquery/1.12.3/jquery.min.js - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633105
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/js/material-bootstrap/0.0.1/material.js - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633107
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/js/bootstrap/3.0.3/bootstrap.min.js - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633109
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/js/jquery-ui/1.11.4/jquery-ui.js - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633110
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/css/material-icons/0.0.1/material-icons.css - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633112
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/js/tutiles.js?v=DSuiteDS2022v10.21PHP7 793:0 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633357
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/js/jscript.js?v=DSuiteDS2022v10.21PHP7 0:0 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633358
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/reserva-clases 28:0 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633358
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/reserva-clases 136:0 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633364
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Light.woff2 - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633410
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Medium.woff2 - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633412
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Regular.woff2 - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633414
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net/fonts/robotocondensed/RobotoCondensed-Regular.ttf - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633422
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/js/procesosWeb.js?v=DSuiteDS2022v10.21PHP7 8:0 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633423
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Light.woff - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633433
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Regular.woff - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633450
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Medium.woff - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633451
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/js/tutiles.js?v=DSuiteDS2022v10.21PHP7 207:12 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633487
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Light.ttf - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633489
    },
    {
        "level": "SEVERE",
        "message": "https://deporsite.centroinsulardedeportesgc.com/reserva-clases 264:1 Uncaught ReferenceError: $ is not defined",
        "source": "javascript",
        "timestamp": 1701954633491
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Medium.ttf - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633492
    },
    {
        "level": "SEVERE",
        "message": "https://resources.deporsite.net//fonts/roboto/Roboto-Regular.ttf - Failed to load resource: the server responded with a status of 404 ()",
        "source": "network",
        "timestamp": 1701954633504
    }
]

**Comment by joergbaier** [comment]
Is your lambda deployed to Europe (Spain) - eu-south-2?

**Comment by vexelgray** [comment]
No, my lambda is currently deployed in the us-east1 region. But that's a great suggestion to try deploying it in the Europe (Spain) - eu-south-2 region. I'll go ahead and deploy it there to see if it makes any difference.

**Comment by vexelgray** [comment]
Wow, you're a lifesaver! 

@joergbaier I can't thank you enough for suggesting the switch to the eu-south-2 region on AWS. It was like waving a magic wand over the issue – the pesky 404 error is gone, and everything is working perfectly now! 

Thanks a million! You've made my day (heck, probably my entire week)! 🎉
