### ISSUE TITLE
[BUG] (likely) Chromium Segfault on ARM - Graviton lambdas, Apple Silicon + Docker Lambda

### ISSUE THREAD

**Issue by alessbelli** [Sparticuz/chromium#19]
## Environment
* `chromium` Version: `107`
* `puppeteer` / `puppeteer-core` Version: `^18.1.0`
* Node.js Version: 16.x
* Lambda / GCF Runtime: `nodejs16.x`, `arm64`

## Expected Behavior

chrome doesn't crash

## Current Behavior

on puppeteer browser start, 
```
Error: Failed to launch the browser process!
/tmp/chromium: /tmp/chromium: cannot execute binary file
```

## Steps to Reproduce

create a lambda with `arm64` architecture (`Architectures: ["arm64"]`)
invoke the following code

```js
const chromium = require('@sparticuz/chromium')
const puppeteer = require('puppeteer-core')

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

## Possible Solution

This is likely because the chromium binary is compiled using x64 as a target.
I believe that for it to work properly, there should be ansible steps to compile for arm, and two different binaries should be present here, then either based on runtime environment detection or based on arguments, the correct executable should be used.

**Comment by alessbelli** [comment]
The above are the exact set of repro steps on lambda. While it's not critical for us to make this work on slightly cheaper lambdas, I believe the same issue prevents development on Apple Silicon macs - which run lambdas using AWS's provided images (`amazon/aws-lambda-nodejs`), which I believe run natively, and therefore run into the same incompatibility when launching chromium built for x86-64

**Comment by Sparticuz** [comment]
Yes, currently this is only for x86-64. This PR from the old package explains more. If you are able to get it working send in a PR! https://github.com/Sparticuz/chrome-aws-lambda/pull/11
