### ISSUE TITLE
[BUG] Can't deploy project serverless-with-lambda-layer

### ISSUE THREAD

**Issue by minhhieple97** [Sparticuz/chromium#194]
When I clone project serverless-with-lambda-layer and run serverless deploy
https://github.com/Sparticuz/chromium/tree/master/examples/serverless-with-lambda-layer
I got this error, Am I missing anything? Thank you for your help!

![image](https://github.com/Sparticuz/chromium/assets/42188983/248bf381-c1e3-4d63-a904-ad2b04817c0f)

**Comment by Sparticuz** [comment]
For that specific example, you need to run `make chromium.zip` in the root directory first to generate the layer.

**Comment by minhhieple97** [comment]
Thank you very much
