### ISSUE TITLE
[Question] Should we use this package instead of the chrome-aws-lambda

### ISSUE THREAD

**Issue by hasan-wajahat** [Sparticuz/chromium#2]
Hey @Sparticuz glad to see you continue working on this. Moving forward should we use this package if we updated our puppeteer  to latest?

Also what I don't fully understand is that you are saying that this is independent from puppeteer but in installation step you mention that we should install a specific preferred version if we want to use puppeteer. Can you explain that a little more?

**Comment by Sparticuz** [comment]
If you don't use any of the puppeteer overrides or hooks, then I would say yes, you should use this package.

What I mean by 'independent from puppeteer', is that `puppeteer` prefers a specific version of `chromium`, see [this](https://pptr.dev/faq/#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy). So to be 100% compatible with puppeteer at any specific time, you should use the version of `chromium` that they recommend, see [this](https://pptr.dev/chromium-support). That means, currently, any version of puppeteer 17.1.0 - 18.0.5 (at this point) should be using chromium 106. So you can use `@sparticuz/chromium@106` for any of those versions. Then when a new version of `puppeteer` requires a new version of chromium, this package will be updated, `@sparticuz/chromium@107`, for example, and that will be compatible with any new version of puppeteer until they update their support to be 108, etc...

Let me know if that makes sense. I can try to clarify the readme if needed.
