### ISSUE TITLE
nodejs 18 support

### ISSUE THREAD

**Issue by BrianHung** [Sparticuz/chromium#20]
Does this library or recent builds (v108) support nodejs 18? I'm using lambda function with nodejs 18 runtime and a lambda layer to deploy the chromium build.

Running into
> Failed to launch the browser process! /tmp/chromium: error while loading shared libraries: libnss3.so

Downgrading the lambda runtime to v16 solves this problem.

**Comment by hunterscavenger** [comment]
@BrianHung my build works perfectly fine with nodejs18 runtime.
