### ISSUE TITLE
[BUG] Navigation failed due to disconnected browser

### ISSUE THREAD

**Issue by FarooqBukhari** [Sparticuz/chromium#200]
## Environment

- `chromium` Version: 119.0
- `puppeteer` / `puppeteer-core` Version: 21.5
- Node.js Version:  16
- Lambda / GCF Runtime: nodejs16

## Expected Behavior

I want to generate a pdf

## Current Behavior

I am getting Navigation Failed error on .setContent()

## Steps to Reproduce

I have a docker based aws lambda. I was previously using @Sparticuz/chrome-aws-lambda which has been archived. Now I can't get this one to work. Help Needed here.
<img width="997" alt="Screenshot 2023-12-11 at 6 29 41 PM" src="https://github.com/Sparticuz/chromium/assets/42795245/79aca634-8ac2-4b14-a1b3-b44f0f1ebe01">

`"use strict";
const chromium = require("@sparticuz/chromium");
const puppeteer = require("puppeteer-core");
const PDF_PARSE = require("pdf-parse");
const pdf2img = require('pdf-img-convert');
const imgToPDF = require('image-to-pdf');
// deps installed and packaged
const AWS = require("aws-sdk");
const AXIOS = require("axios");
// local file imports
const config = require("./config");
//Set up SQS
const SQS = new AWS.SQS({ apiVersion: "2012-11-05" });
process.env.FONTCONFIG_PATH = "/usr/share/fonts/truetype";
module.exports.handleResponse = async (event, context) => {
  // received an Amazon SQS event
  console.log("Event: ", event);
  console.log("Context: ", context);
  console.log("Received records: ", event.Records.length);
  let browser = null;
  try {
    // TODO: pull out browser initialization from loop
    console.log(chromium.args);
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
    console.log("browser created");
    const s3 = new AWS.S3();
    // event can have multiple records
    for (let record of event.Records) {
      const body = JSON.parse(record.body);
      console.log("Processing record: ", body);
      // This can act as a blueprint of the request object
      const {
        bucket,
        key,
        fileName,
        responseUrl,
        html,
        wfItemUuid,
        successWfEvent,
        failureWfEvent,
        language,
      } = body;
      // const bucket = body["bucket"], key = body["key"], fileName = body["fileName"],
      //   responseUrl = body["responseUrl"], html = body["html"], wfItemUuid = body["wfItemUuid"],
      //   successWfEvent = body["successWfEvent"], failureWfEvent = body["failureWfEvent"];
      const response = {
        wfItemUuid,
        fileName,
        wfEvent: failureWfEvent,
        generationTimestamp: new Date().getTime(),
        message: null,
      };
      try {
        let message = null;
        let page = null;
        console.log("generating pdf");
        page = await browser.newPage();
        await page.setContent(html, { waitUntil: ["networkidle0", "load", "domcontentloaded"] });
        let pdf = await page.pdf(config.getConfig(language));
        console.log("Language: " + language);
        const pdfInfo = await PDF_PARSE(pdf); //numpages
        if (pdfInfo.numpages > 2) {
          message = "generated pdf has more than 2 pages";
        } else {
          console.log("flattening image");
          try {
            const pngPages = await pdf2img.convert(pdf, {
              width: 596*4, //Number in px
              height: 842*4, // Number in px
              page_numbers: [1, 2], // A list of pages to render instead of all of them
              base64: true,
              scale: 2.0
            });
            const pages = [
                "data:image/png;base64,"+pngPages[0],
                "data:image/png;base64,"+pngPages[1]
            ]
            pdf = imgToPDF(pages, imgToPDF.sizes.A4);
          }
          catch (err) {
            console.log(err);
            message = "failure in flattening pdf";
          }
          console.log("uploading to s3");
          try {
            const uploadResponse = await s3
              .upload({
                Body: pdf,
                Bucket: bucket,
                Key: key,
              })
              .promise();
            console.log(uploadResponse);
          } catch (err) {
            console.log(err);
            message = "failure in uploading the generated pdf to s3";
          }
        }
        if ("local" == process.env.ENVIRONMENT) {
          console.log("sending lambda response to", responseUrl);
          await AXIOS.post(
            responseUrl,
            !message
              ? { ...response, wfEvent: successWfEvent }
              : { ...response, message }
          )
            .then(function (r) {
              console.log("lambda response sent", r);
            })
            .catch(function (e) {
              console.log("lambda response failed", e);
            });
        } else {
          // call sendSQS message
          await sendSQS(response, successWfEvent, message);
        }
        if (page !== null) {
          await page.close();
        }
      } catch (error) {
        console.log("error processing record: ", record, error);
      }
    } // for loop ends
  } catch (error) {
    console.log("error in function body: ", error);
    return context.fail(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
};`

**Comment by amansatija** [comment]
hey i am facing the same issue

**Comment by puja2718** [comment]
Hi, I am facing the same issue, any update on this?

**Comment by amansatija** [comment]
@Sparticuz can u please test this i m getting this on all versions of chromium (116 to 119 )with puppeteer(21.1.0 to 21.5.2) from using sam application 
the following is my code for pdf handling

**Comment by anevsevra** [comment]
I have the same issue in AWS Lambda, runtime is Node.js 20.x. However, exactly the same code works properly in local environment (Linux x86_64). I figured out that in my case lambda throws an error if HTML string contains `<img />` tags. Without them lambda generates PDF without issues. Images, that are put in HTML, are hosted on CDN.

**Comment by puja2718** [comment]
Yes, I am facing the same issue when html contains <img /> tags.
However, I was able to apply a workaround by using `await page.setRequestInterception(true)`
So, intercept any requests made to external urls and apply your own logic.

For example, this works for me:
`    await page.setRequestInterception(true);
    page.on('request', async (interceptedRequest: any) => {
      if (
        interceptedRequest.url().endsWith('.png')
        || interceptedRequest.url().endsWith('.jpg')
        || interceptedRequest.url().endsWith('.jpeg')
      ) {
        const data = await axios.get(interceptedRequest.url(), {
          responseType: 'arraybuffer',
        }).catch((e) => logger.error(e));
        interceptedRequest.respond({
          body: data.data,
        });
      } else {
        interceptedRequest.abort();
      }
    });`

**Comment by jonathanwsilva** [comment]
This might be the same issue as the other two recent bugs
https://github.com/Sparticuz/chromium/issues/196
https://github.com/Sparticuz/chromium/issues/201

Namely, it seems like amazon has pushed build images starting on 12/05 that break this library.
Turn on `dumpio:true` in your launch options and see if you can find any more data in the chromium logs.

Also try the workaround in the other two issues, maybe stipulating an older runtime release in your `--invoke-image` could sort this out for you, for now.

**Comment by jennydale** [comment]
We are having this issue too.

The workaround @puja2718 posted Dec 13 worked for us, hooray! Only real modifications I made to that snippet were to check that the start of the url was 'http', because axios couldn't fetch `file://whatever/whatever.png` images, and to continue rather than abort non-matching requests:

```
    await page.setRequestInterception(true)
    page.on('request', async interceptedRequest => {
        // This part may not be needed since this is our only interceptor, but docs talk a lot about it, and it seems like it shouldn't hurt...
        if (interceptedRequest.isInterceptResolutionHandled()) return
        const url = interceptedRequest.url()
        if (
            url.startsWith('http') &&
            (url.endsWith('.png') ||
                url.endsWith('.jpg') ||
                url.endsWith('.jpeg'))
        ) {
            const data = await axios
                .get(interceptedRequest.url(), {
                    responseType: 'arraybuffer',
                })
                .catch(e => {
                    log('ERROR', e)
                })
            await interceptedRequest.respond({ body: data.data })
        } else {
            await interceptedRequest.continue()
        }
    })
```

Still feels pretty icky to have this in the codebase, so hoping the issue gets resolved soon so we can remove this workaround.
