### ISSUE TITLE
[QUESTION] Building local docker on an ARM64 with an x86 chromium binary

### ISSUE THREAD

**Issue by FreddieFruitSticks** [Sparticuz/chromium#202]
## Question

Hi Sparticuz team! I see that ARM64 is not supported yet. I am trying to build my lambda using docker, which makes lambda layers a little trickey. 

I am thinking of building a docker image with the x86 chromium binary in a base image to my lambda image. Then pass the chromium binary path to the executablePath variable. 

Do you have any suggestions on how to go about doing this?

## Why would it be useful?

I feel this could be an alternative solution to lambda layers

**Comment by oluSammy** [comment]
@FreddieFruitSticks did you figure this out?

**Comment by FreddieFruitSticks** [comment]
No Sir, I did not. I eventually got to installing the chromium binary, but then realised when running it that I needed to install all the ARM64 dependencies. This proved to be a nightmare, and thought of maintaining them haunted my dreams. 

I feel like a much better solution is to get an X86 ec2 instance up, and build and deploy from there.

**Comment by Sparticuz** [comment]
If you are using a custom docker image, you should just install chromium in the dockerfile.
