### ISSUE TITLE
[REQUEST] Executable path from npm package

### ISSUE THREAD

**Issue by mdjfs** [Sparticuz/chromium#205]
## What would you like to have implemented?

Hello, what's up. Is possible have a npm package with all tars available to install an specific version of chromium binary? For my case, i need a .tar under <50MB to fit into vercel lambda, but can't be hosted in a remote server because fetching increases the max timeout (10s) then i need the binary in a node module to use it more faster. Then, to pick a binary under <50MB needs to be a specific version (older chromium versions has a size like 45mb for example)

## Why would it be useful?

Something like that:

```
yarn add @sparticuz/chromium-bin@110.0.1
```

_equivalent to chromium-v110.0.1-pack.tar_

```
const browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath(
            "@sparticuz/chromium-bin"
        ),
        headless: chromium.headless,
        ignoreHTTPSErrors: true,
    });
```

**Comment by Sparticuz** [comment]
Unfortunately, no. chromium is larger than 50 megs compressed. If you do some research to get a smaller build, feel free to submit a PR
