### ISSUE TITLE
[REQUEST] set custom binary file name

### ISSUE THREAD

**Issue by vitaliy-v** [Sparticuz/chromium#212]
## What would you like to have implemented?
Add an option to set the different name for the binary chrome file, so instead 'chromium' set 'chromium-1' or any.

As a new option, for example customName

## Why would it be useful?
When we run browser in AWS Lambda with web scrapping Crawlee and want to use AutoscaledPool to run crawlers simultaneously we can't do that because /tmp/chromium is locked and get an error. The idea is when we extract file to /tmp use different names to avoid that. Then we can run many browsers in AWS Lambda and scrapping will be much faster.

**Comment by Sparticuz** [comment]
Probably not. You should just run parallel lambdas
