### ISSUE TITLE
AWS layers issue

### ISSUE THREAD

**Issue by zielaty** [Sparticuz/chromium#215]
I am trying to figure out how to use layers that are available [here](https://github.com/Sparticuz/chromium/releases) in my  AWS lambda written in TypeScript.

I initially thought that I can just point puppeteer to the folder where the chromium binary is located. Which happens to be under /opt/nodejs/node_modules/@sparticuz/chromium/bin at runtime. But I realized that this folder contains the .br file that is compressed chromium rather than decompressed one.

What is supposed to trigger the decompression? I am really confused. Appreciate any help on this.

**Comment by Sparticuz** [comment]
Calling executablePath will decompress the files. Check out the examples. You shouldn't need to specify a path if everything is standard.
