### ISSUE TITLE
Can't add Chromium layer to Lambda, size too big

### ISSUE THREAD

**Issue by kuda1992** [Sparticuz/chromium#217]
## Environment

- `chromium` Version: `119.0.2`
- `puppeteer` / `puppeteer-core` Version:  `21.7.0`
- Node.js Version:  `18.x` 
- Lambda / GCF Runtime:  `nodejs18.x` 

## Expected Behavior
I am using Lambda to download PDFs with Puppeteer. I have followed the instructions on the wiki. However, I am getting an error when adding the chromium layer to the Lambda. The size is too big. 

I am using this arn 
arn:aws:lambda:eu-west-2:764866452798:layer:chrome-aws-lambda:41

<img width="958" alt="Screenshot 2024-01-13 at 18 18 00" src="https://github.com/Sparticuz/chromium/assets/35928491/68a8588d-349e-46e5-8ec1-bcf77b43affe">

**Comment by Sparticuz** [comment]
I think most of the time these restrictions are in the web version of AWS console. If you are able, try attaching the arn on CLI console and see if it gives you a size error.

**Comment by kuda1992** [comment]
I am 100% convinced it's not the web console. I have tried various methods to attach the layer to a lambda, including the serverless framework and AWS CLI. However, I still get the same error. The layer is just too big for lambda size quotas. I am surprised it's worked for everyone else.

**Comment by owenvoke** [comment]
Also hitting this issue with `119.0.2` through both AWS CLI and the web interface.

**Comment by Sparticuz** [comment]
Unfortunately, there isn't much to be done here. You might need to switch to @sparticuz/chromium-min
