### ISSUE TITLE
[BUG] Truncated Screenshots in AWS Lambda Using Puppeteer and Chromium

### ISSUE THREAD

**Issue by gibykthomas** [Sparticuz/chromium#218]
## Environment

- `@sparticuz/chromium` Version: `118.0.0`
- `puppeteer-core` Version: `21.4.1`
- Node.js Version: `18`
- LambdaRuntime:  `nodejs18.x`

## Expected Behavior

I expected the entire content of the HTML page to be captured in the screenshot without being truncated.

## Current Behavior

When running Puppeteer with Chromium in AWS Lambda, the screenshots of certain HTML pages are getting truncated, not capturing the full content as expected

## Steps to Reproduce

html file attached 
[html.pdf](https://github.com/Sparticuz/chromium/files/13931278/html.pdf)

code

```const chromium = require('@sparticuz/chromium');
const puppeteer = require("puppeteer-core");
const AWS = require('aws-sdk');
const uuidv4 = require('uuid').v4;

AWS.config.update({
  region: process.env.region, 
  signatureVersion: 'v4',
});

const s3 = new AWS.S3();

exports.handler = async (event, context) => {
  let browser = null;

  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
    let html = event.body
    let page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const screenshot = await page.screenshot({fullPage: true,type: 'png' });

    const s3Params = {
      Bucket: process.env.bucket, 
      Key: `image_${Date.now()}_${uuidv4()}.png`, 
      Body: screenshot,
      ContentType: 'image/png',
      ACL: 'private' 
    };

    await s3.upload(s3Params).promise();

    // Create a presigned URL
    const urlParams = {
      Bucket: s3Params.Bucket,
      Key: s3Params.Key,
      Expires: parseInt(process.env.expiry) 
    };
    const presignedUrl = s3.getSignedUrl('getObject', urlParams);
    return  {
      statusCode: 200,
      body: JSON.stringify({
        url: presignedUrl,
      }),
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Allow-Methods': '*'
      },
    } 
  } catch (error) {
    console.error("Error:", error);
    throw new Error("Failed processing request");
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
};
```

**Comment by Sparticuz** [comment]
You'll want to look at puppeteers viewport settings most likely.

**Comment by gibykthomas** [comment]
Thanks for the reply. The `setViewport` settings is not helping.

**Comment by gibykthomas** [comment]
solved the issue by providing the following args

args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',
        '--single-process',
        '--disable-web-security',
        '--font-render-hinting=none',
      ]

**Comment by mwcbrent** [comment]
@gibykthomas thanks for posting the resolution, this solved a similar issue where I observed pages tiling on top of themselves.
