### ISSUE TITLE
[BUG] Error: spawn Unknown system error -8

### ISSUE THREAD

**Issue by hassanAdamineJad** [Sparticuz/chromium#222]
## Environment

- `chromium` Version: 119.0.2
- `puppeteer` / `puppeteer-core` Version: 21.5.0
- Node.js Version:  20.x
- Lambda / GCF Runtime:  nodejs20.x

## Expected Behavior
I expected work with the node js20.x and start to scrape urls

## Current Behavior
 I got this error `✖ Error: spawn Unknown system error -8` in local and `errorMessage": "The input directory \"/var/task/src/deliverect/bin\" does not exist.` in the AWS lambda

**Comment by aaronjameslang** [comment]
Are you running locally on an M series mac? I got `Error: spawn Unknown system error -8` locally on my mac but not my linux machine. Workarounds for this are presented in the readme, if you are on a mac.

I got `The input directory "/var/bin" does not exist` on AWS Lambda also, if I work it out I'll let you know.

**Comment by aaronjameslang** [comment]
My issue was that the bundler I was using wasn't including the bin dir, and when I forced that it was too big. Now I'm moving to use layers.

How are you getting the binary files to the lambda? Layers? S3 url? Can you share some code?

**Comment by willybaer** [comment]
I had a similiar issue. But now my puppeteer service is running on Netlify without any problem. Here is how I do setup the browser instance.

`
import Chromium from "@sparticuz/chromium";
import puppeteer, { Browser } from "puppeteer-core";


const config = {
      args: process.env.NODE_ENV !== 'production' ? puppeteer.defaultArgs() : Chromium.args,

      defaultViewport: Chromium.defaultViewport,
      executablePath: process.env.NODE_ENV !== 'production' 
        ? "/tmp/localChromium/chromium/mac_arm-1255063/chrome-mac/Chromium.app/Contents/MacOS/Chromium"
        : await Chromium.executablePath('https://github.com/Sparticuz/chromium/releases/download/v121.0.0/chromium-v121.0.0-pack.tar')
      ,
      headless: process.env.NODE_ENV !== 'production' ? false : Chromium.headless,
      ignoreHTTPSErrors: true,
    };
    const browser = await puppeteer.launch(config);
`
and

"puppeteer-core": "21.9.0",
"@sparticuz/chromium": "^121.0.0",

**Comment by ashramsey** [comment]
> I got The input directory "/var/bin" does not exist on AWS Lambda also, if I work it out I'll let you know.

@aaronjameslang any luck with this? I'm not having finding any :-(

**Comment by ashramsey** [comment]
hot diggity!

`await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin')` works for me with v123.0.0.

**Comment by IgnasKav** [comment]
@ashramsey which version of puppeteer-core are you using?

**Comment by ashramsey** [comment]
> @ashramsey which version of puppeteer-core are you using?

@IgnasKav "puppeteer-core": "^22.6.0",
