### ISSUE TITLE
TypeScript issue with `headless` param in `puppeteer-core = 22.2.0` and `@sparticuz/chromium = 122.0.0`

### ISSUE THREAD

**Issue by turakvlad** [Sparticuz/chromium#234]
It looks like new `puppeteer-core` expects `boolean` or `"shell"` in the `headless` param but `@sparticuz/chromium` used old `"chrome-headless-shell"`.

Is that correct to say that we can just use `true` instead of `chromium.headless` if we use Chromium 112+?

<img width="1121" alt="image" src="https://github.com/Sparticuz/chromium/assets/7996184/8e2684c7-3eaf-44af-95c5-ce0670514771">

Thanks!

**Comment by Sparticuz** [comment]
Ah, you are right. The PR that this is from is https://github.com/puppeteer/puppeteer/pull/11815. While the description of the PR states `chrome-headless-shell`, there is another commit that changes it to just `shell`.
