### ISSUE TITLE
Chromium or Firefox for Android

### ISSUE THREAD

**Issue by emadmahdi** [Sparticuz/chromium#248]
Hello,
1. 
Thank you for publishing this project .. It is a brilliant idea.

2.
I need to do exactly the same but using Firefox Browser and Android OS .. Is this possible ?!

3.
Why Firefox .. Because the headless Chrome browser fail bypassing the Cloudflare turnstile page (I'm Under Attack Mode, IUAM).

4.
Why Android .. Because it requires the web browser to be installed on a different user/environment than Selenium or Playwright .. which make it very hard to setup the browser for regular simple users.

5.
Is this possible ?!

.

**Comment by Sparticuz** [comment]
Not sure, feel free to post back here is you figure it out.
