### ISSUE TITLE
[BUG] AWS Amplify - NextJS - EACCES permission denied root/.config/puppeteer

### ISSUE THREAD

**Issue by bhaktatejas922** [Sparticuz/chromium#251]
## Environment

    "@sparticuz/chromium": "^123.0.0",
    "puppeteer-core": "^22.6.1",
- Node.js Version: 
![Screenshot 2024-04-02 at 3 22 23 PM](https://github.com/Sparticuz/chromium/assets/26863466/20426bdd-d168-4b4d-9f8c-c5d5c44d6411)

- Lambda / GCF Runtime: 
EACCES: permission denied, stat '/root/.config/puppeteer'

`  const browser = await puppeteer.launch(
    process.env.NODE_ENV === 'production'
      ? {
          args: chromium.args,
          defaultViewport: chromium.defaultViewport,
          executablePath: await chromium.executablePath(),
          headless: chromium.headless,
          ignoreHTTPSErrors: true,
        }
      : {
          headless: false,
          executablePath: executablePath(),
        },
  );`

**Comment by Sparticuz** [comment]
seems like a puppeteer issue?
