### ISSUE TITLE
[BUG] setGraphicsMode causes issue "Network.enable timed out"

### ISSUE THREAD

**Issue by alexw23** [Sparticuz/chromium#260]
## Environment

- **Chromium Version**: 123.0.1
- **Puppeteer Version**: 22.6.5
- **Node.js Version**: 20.x
- **AWS Lambda Runtime**: 20.x

## Expected Behavior

The script should execute without any errors, successfully opening a web page and returning the title.

## Current Behavior

When running the script, the following timeout error related to the `Network.enable` command is produced:

```json
{
    "errorType": "ProtocolError",
    "errorMessage": "Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.",
    "trace": [
        "ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.",
        "    at <instance_members_initializer> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)",
        "    at new Callback (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)",
        "    at CallbackRegistry.create (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)",
        "    at Connection._rawSend (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:26)",
        "    at CdpCDPSession.send (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)",
        "    at NetworkManager.addClient (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/NetworkManager.js:70:20)",
        "    at FrameManager.initialize (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/FrameManager.js:179:38)",
        "    at #initialize (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:311:36)",
        "    at CdpPage._create (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:97:31)",
        "    at /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Target.js:198:42"
    ]
}
```

## Steps to Reproduce

Run the suggested [hello world script](https://github.com/Sparticuz/chromium?tab=readme-ov-file#usage) on an AWS Lambda environment. Here's how to reproduce the issue:

1. Set up the AWS Lambda environment with Node.js 20.x runtime.
2. Deploy the following Node.js script to Lambda:

```js
const puppeteer = require("puppeteer");
const chromium = require("@sparticuz/chromium");

module.exports.run = async (event) => {
  chromium.setHeadlessMode = true;

  // Disabling WebGL for compatibility; set to false if not needed.
  chromium.setGraphicsMode = false;

  // Load custom fonts if necessary (optional).
  await chromium.font("https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf");

  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });

  const page = await browser.newPage();
  await page.goto("https://example.com");
  const pageTitle = await page.title();
  await browser.close();

  return {
    statusCode: 200,
    body: JSON.stringify({
      message: pageTitle,
    }),
  };
};
```

3. You should get the following output:

```json
{
    "errorType": "ProtocolError",
    "errorMessage": "Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.",
    "trace": [
        "ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.",
        ...
    ]
}
```

## Possible Solution

The error can be mitigated by adjusting the order of the `setGraphicsMode` property assignment:

```js
  // Launch the Puppeteer browser instance first.
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });

  // Set the graphics mode after launching the browser.
  chromium.setGraphicsMode = false;
```

Which produces the correct result.

```json
{
    "statusCode": 200,
    "body": "{\"message\":\"Example Domain\"}"
}
```

Not sure what this means however and if graphicsMode is actually disabled now or not.

**Comment by kurtisz** [comment]
+1

**Comment by jmandawg** [comment]
+1

**Comment by alexw23** [comment]
> Thanks @alexw23 this hack or fix literally saved us. 

Good to hear! Took a few hours of debugging to figure this one out.

**Comment by mharis** [comment]
What is going on with this one? Very weird.

Did AWS change something with Lambda?

**Comment by Sparticuz** [comment]
> The error can be mitigated by adjusting the order of the setGraphicsMode property assignment:
> Not sure what this means however and if graphicsMode is actually disabled now or not.

It would not be disabled, however. For now, this is correct. (keeping graphicsMode enabled, not the order of the commands, which is incorrect)

A change in Chromium is to blame. Unfortunately, I don't have any insight into the error or how to fix it. The next version of this package will actually force it to always be true, even if the user disabled it.

**Comment by alexw23** [comment]
Should this option be removed from readme then? What's the main benefit of disabling graphics mode?

**Comment by nitin-1926** [comment]
This was a lifesaver. A big thanks @alexw23 🙇🏻 , cannot explain how much this helped. This is 💎.
Would love to know how were you able to find this out??

**Comment by alexw23** [comment]
> Would love to know how were you able to find this out??

I updated chromium versions and it was working locally but not lambda, so in another file within our project I tried a minimum set of options (for chromium.launch) and it worked in lambda.

So I started reducing our chromium.launch config line by line, `setGraphicsMode` was one of the last few I removed so it took a while given I had to deploy and wait just for each line.

Anyway looking at this further it seems changing the order means nothing. According to readme (You can disable WebGL by setting chromium.setGraphicsMode = false; **before** launching Chromium.) Thus if placed after it will have no effect, so rather `chromium.setGraphicsMode` needs to be removed, will update my issue shortly.
