### ISSUE TITLE
[BUG]    const page = await context.newPage() wont work

### ISSUE THREAD

**Issue by wanghaisheng** [Sparticuz/chromium#267]
## Environment

- `chromium` Version:Chromium: 123.0.6312.0
- `playwright` / `playwright-core` Version:1.42.0 or 1.42.1
- Node.js Version: 18.x
- Vercel  Runtime: 18.x

## Expected Behavior
I  have tried both playwright version,
and  also try to use     const page = await browser.newPage(),
all failed 

```
    const browser = await playwright.launch({
      args: sparticuzChromium.args,

      executablePath: await sparticuzChromium.executablePath("https://github.com/Sparticuz/chromium/releases/download/v123.0.0/chromium-v123.0.0-pack.tar"),
      headless: sparticuzChromium.headless,
    })
    console.log("Chromium:", await browser.version())

    const context = await browser.newContext()
    console.log("new context")

    const page = await context.newPage()
    console.log("new page")
```
should print new page
## Current Behavior
log only get context
```
new context

```
## Steps to Reproduce

git clone https://github.com/wanghaisheng/ahref-free-tool-api
run on vercel and change runtime to 18.x

**Comment by Xocix** [comment]
happening to me as well out of nowhere, been running it for several months without issues:
"@sparticuz/chromium": "^116.0.0",
"puppeteer-core": "^21.1.1"

**Comment by jmandawg** [comment]
Did you try to remove this line:
```
chromium.setGraphicsMode = false;
```

**Comment by francobasilico** [comment]
Hey @wanghaisheng did you sort the problem? I'm having the same issue since april?
