### ISSUE TITLE
Misunderstanding in example

### ISSUE THREAD

**Issue by jeremyquinton** [Sparticuz/chromium#277]
In this example here
https://github.com/Sparticuz/chromium/blob/master/examples/serverless-with-lambda-layer

On line 19 of the serverless.yml 
https://github.com/Sparticuz/chromium/blob/master/examples/serverless-with-lambda-layer/serverless.yml#L19

There is a reference to chromium.zip. I'm guessing this is the chromium binary. Do I just download the correct version of chromium as a zip to use ?

That is not entirely clear to me and I've read the readme over and over. Happy to do a pull request with the answer to this question and and a readme to this example.

**Comment by Sparticuz** [comment]
It is referencing the chromium.zip file made by the Makefile. Yes, that's the release zip (layer version).
