### ISSUE TITLE
[REQUEST] Update chromium version

### ISSUE THREAD

**Issue by supriyo-biswas** [Sparticuz/chromium#281]
I'd like to use a more recent version of Puppeteer, and would therefore like to have the latest version of Chromium (currently at 126.x as per https://pptr.dev/supported-browsers) for this purpose.

Thank you for this useful project!

**Comment by Sparticuz** [comment]
I've been having some issues compiling it but I am working on it

**Comment by supriyo-biswas** [comment]
Maybe you could tell me about the issues that you've faced so that I can help in any way I can?

Personally the issue I've faced is with cloning the Chromium sources; when I point it at the newest Puppeteer revision the process runs for quite a bit, before the Ansible script simply terminates (perhaps due to a timeout)?

**Comment by stephankaag** [comment]
I have Chromium 120.x and 121.x binaries available for download (only Amazon 2 for now, will build for Amazon 2023 asap).

[Chromium 120](https://github.com/chromium-for-lambda/chromium-binaries/releases/tag/arm64-amazon-linux-2-chromium-120.0.6099) (For Playwright v1.40.1 , v1.40.0 & Puppeteer v21.8.0)
[Chromium 121](https://github.com/chromium-for-lambda/chromium-binaries/releases/tag/arm64-amazon-linux-2-chromium-121.0.6167) (For Playwright v1.41.2 , v1.41.1 , v1.41.0 & Puppeteer v22.1.0 , v22.0.0 , v21.11.0 , v21.10.0 , v21.9.0)

**Comment by Sparticuz** [comment]
It's an llmv compilation error. If you have working code for arm, I would appreciate a PR. Ive not had time to look into the issue.

**Comment by supriyo-biswas** [comment]
@stephankaag 

Please keep offtopic comments promoting your commercial initiatives away from this thread, since you're already aware that the versions that you linked above are already provided by this project and only serves to promote your own project.

Not to mention that without the build sources being provided, we can't really trust what you are distributing.

Thank you.

**Comment by basavaraj31** [comment]
@Sparticuz when we can expect the new version of @sparticuz/chromium with chromium 126.X.X

**Comment by supriyo-biswas** [comment]
@basavaraj31 

At this point this thread is doomed to be a repeat of the famous [mitmproxy issue](https://github.com/mitmproxy/mitmproxy/issues/6051); please don’t be that guy.
