### ISSUE TITLE
[BUG] puppeteer-core gives time out error when used with latest version of Chromium (123.0.0)

### ISSUE THREAD

**Issue by Madhumitha2911** [Sparticuz/chromium#283]
## Environment
Node js running in AWS lambda

- `chromium` Version: 123.0.1
- `puppeteer` / `puppeteer-core` Version: 22.13.0
- Node.js Version: v20.10.0.
- Lambda / GCF Runtime: Node.js 20.x

## Current Behavior

await browser.newPage()  doesn't resolve
gives time out error

## Steps to Reproduce

```js
chromium.setGraphicsMode = false
  const browser: Browser = await puppeteer.launch({
    executablePath: await chromium.executablePath(),
    args: [...chromium.args, '--font-render-hinting=none'],
    defaultViewport: {
      width: 1192,
      height: 794
    },
    headless: true
  })

  const page: Page = await browser.newPage()
```

**Comment by Sparticuz** [comment]
setGraphicsMode has a bug, turn it to true
