### ISSUE TITLE
[BUG] Pupeteer-core not available in lambda

### ISSUE THREAD

**Issue by maderlock** [Sparticuz/chromium#288]
## Environment

- `chromium` Version: v126.0.0
- `puppeteer` / `puppeteer-core` Version: ?
- Node.js Version: 18.x
- Lambda Runtime: `nodejs18.x`

## Expected Behavior

Puppeteer code run with chromium on lambda

## Current Behavior

Error when attempt to run: `Cannot find package 'puppeteer-core' imported from /var/task/index.mjs`

## Steps to Reproduce

The following is the `index.mjs`:

```js
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

export const handler = async (event) => {
const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
};
```

I get the same results when I build ising the instructions in https://github.com/Sparticuz/chromium?tab=readme-ov-file#aws-lambda-layer or directly use a release from https://github.com/Sparticuz/chromium/releases or reference a layer from https://github.com/shelfio/chrome-aws-lambda-layer

## Possible Solution

All the instructions I can find for using a lambda layer suggest that puppeteer-core is included and does not need to be separately added to a layer, but I cannot see any proof of its presence in the zip files created. So is the issue here just one of clarifying documentation?

**Comment by Sparticuz** [comment]
Puppeteer-core is not included and must be a direct dependency in your package.json. See https://github.com/Sparticuz/chromium?tab=readme-ov-file#install
