### ISSUE TITLE
[UPSTREAM] chromium no longer works on GCF

### ISSUE THREAD

**Issue by Dobermensch** [Sparticuz/chromium#29]
## Environment
* `chromium` Version: 109
* `puppeteer` / `puppeteer-core` Version: 19.4.0
* Node.js Version:  16
* Lambda / GCF Runtime:  GCF nodejs16.x

## Expected Behavior

should work

## Current Behavior

```
2022-12-27 15:57:01.428 HKT
function-1gf78lu3116xn Function execution started
2022-12-27 15:57:01.443 HKT
function-1gf78lu3116xn Function execution took 14 ms, finished with status: 'ok'
2022-12-27 15:57:01.466 HKT
function-1gf78lu3116xn Error: spawn EFAULT at ChildProcess.spawn (node:internal/child_process:420:11) at Object.spawn (node:child_process:733:9) at BrowserRunner.start (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:120:34) at ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:74:16) at async main (/workspace/index.js:40:21) {
2022-12-27 15:57:01.466 HKT
function-1gf78lu3116xn errno: -14,
2022-12-27 15:57:01.466 HKT
function-1gf78lu3116xn code: 'EFAULT',
2022-12-27 15:57:01.466 HKT
function-1gf78lu3116xn syscall: 'spawn'
2022-12-27 15:57:01.466 HKT
function-1gf78lu3116xn }
```

## Steps to Reproduce

```js
const puppeteer = require('puppeteer-core');
const chromium = require('@sparticuz/chromium');

exports.helloPubSub = (event, context) => {
  const main = async () => {
  try {

    const browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
...
  }
}
```

**Comment by Sparticuz** [comment]
You should be able to find the output of chromium, the error seems to say there is a problem launching it.

**Comment by Sparticuz** [comment]
https://pptr.dev/troubleshooting#running-puppeteer-on-google-cloud-functions

It appears that GCF might not work anymore

**Comment by Sparticuz** [comment]
If someone can figure out what the dependencies are, they can be added as a `bin/gcf.tar.br` file, similar to what is done for aws.

**Comment by aldenquimby** [comment]
Possibly related: https://issuetracker.google.com/issues/266279679?pli=1

**Comment by humanismusic** [comment]
It looks like the linked issue, [[Add libnss3.so to Node 18 runtime so that Puppeteer can work [on GCF]](https://issuetracker.google.com/issues/266279679?pli=1)](https://issuetracker.google.com/issues/266279679?pli=1) has now been resolved so this should work now on Google Cloud Functions using the Node 18 runtime.

**Comment by Sparticuz** [comment]
If someone wants to confirm if it works, we can close this issue.

**Comment by TrevorSundberg** [comment]
@Sparticuz Found this issue from running into the `EFAULT` on the Node 16 runtime on GCF, upgraded to 18 just today and I'm able to run :)

**Comment by itismejy** [comment]
I cannot run on node v23.3.0, getting this error:
Error: spawn EFAULT
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at Object.spawn (node:child_process:762:9)
    at new Process (/workspace/node_modules/puppeteer-core/node_modules/@puppeteer/browsers/lib/cjs/launch.js:103:56)
    at launch (/workspace/node_modules/puppeteer-core/node_modules/@puppeteer/browsers/lib/cjs/launch.js:50:12)
    at ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:77:54)
