### ISSUE TITLE
[REQUEST] update to Chromium 128.x and 129.x

### ISSUE THREAD

**Issue by DAcodedBEAT** [Sparticuz/chromium#303]
## What would you like to have implemented?

since puppeteer 23.2.0 (released on 2024-08-26), it has targeted 128 and the last released version of this project is 127.

update [2024-09-18]: https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v23.4.0 Puppeteer 23.4.0 came out, which now targets Chromium 129.0.6668.58

## Why would it be useful?

ensuring that dependencies are up to date

**Comment by Sparticuz** [comment]
Sorry, 129 going live now
