### ISSUE TITLE
How to prevent chromium from breaking?

### ISSUE THREAD

**Issue by necky2** [Sparticuz/chromium#321]
I was running `@sparticuz/chromium` at `129.0.0` and `playwright-core` at `1.48.0` in a Nextjs app, deployed to Vercel with this code:

```
import chromium from "@sparticuz/chromium";
import playwright from "playwright-core";
const executablePath = await chromium.executablePath();
const browser = await playwright.chromium.launch({
  executablePath,
  headless: true,
  args: [...chromium.args,   "--no-sandbox", "--disable-setuid-sandbox", "--disable-gl-drawing-for-tests",],
});
....
```

Suddenly, it broke in production with the following error. It possibly broke with a deployment, but the lock file was never changed.
`[pid=25][err] /tmp/chromium: error while loading shared libraries: libnspr4.so: cannot open shared object file: No such file or directory`

I upgraded `@sparticuz/chromium` to `131.0.1` and `playwright-core` to `1.49.0`, which fixed the issue.

I have 2 questions:
1. What was the cause of this problem? I can provide more info if needed
2. How can I prevent this happening in production in the future?

**Comment by Sparticuz** [comment]
That error means the environment changed, most likely on deploy. There are dependencies that need to be extracted on each run, and they are different depending on if the serverless function is Amazon Linux 2 (<= node 18), or Amazon Linux 2023 (>= node 20)

If the environment is unable to be detected, no dependencies are extracted, which means they must be installed in the container the function is run in. If they are not, you will get that type of error.

I'm guessing maybe Vercel upgraded your functions to node 22, which support was added in 131.0.1

I would say, to avoid these types of errors, to have a completely separate function dedicated to running chromium. I would decouple it from any type of user input, being run on a SQS payload. That way payloads could be retried on failure and also your users are not blocked for the very slow process of running chromium. I would also deploy it straight to Lambda, not through Vercel. That way you have complete control of your environment.

**Comment by necky2** [comment]
Thanks for the response. I will consider these tips to improve reliability and performance.

I checked the logs and you are right about the cause. Node was upgraded to v22, even though I have v20 in Vercel settings. It was overridden by "engines" setting in package.json.

This was in the logs:
```
Warning: Due to "engines": { "node": ">=20" } in your `package.json` file, the Node.js Version defined in your Project Settings ("20.x") will not apply, Node.js Version "22.x" will be used instead. Learn More: http://vercel.link/node-version
Warning: Detected "engines": { "node": ">=20" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version 
```
