### ISSUE TITLE
headless: false chromium browser is not opening

### ISSUE THREAD

**Issue by kaykhan** [Sparticuz/chromium#38]
When i set headless to false to see the chromium browser so i can debug. No browser loads, but the function does finish successfully returning the title. Even tried to remove the headless prop

```
   const browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath(),
        ignoreHTTPSErrors: true,
        headless: false
    });

    const page = await browser.newPage();
    await page.goto("https://example.com");
    const pageTitle = await page.title();
    console.log(pageTitle);
    //await browser.close();
```

```
   "@sparticuz/chromium": "^109.0.6",
    "puppeteer-core": "^19.4.0",
```

**Comment by Sparticuz** [comment]
How are you testing this? What OS, environments, etc...?

**Comment by Sparticuz** [comment]
If NODE_ENV is set to testing it will always run headless, you can try commenting out this line https://github.com/Sparticuz/chromium/blob/c7284f47ea15badc27087810386858b77e62908b/source/index.ts#L234

**Comment by kaykhan** [comment]
> If NODE_ENV is set to test it will always run headless, you can try commenting out this line
> 
> https://github.com/Sparticuz/chromium/blob/c7284f47ea15badc27087810386858b77e62908b/source/index.ts#L234

I wonder if `sls invoke local -f` runs with NODE_ENV test, i will have to test that theory tomorrow.

**Comment by kaykhan** [comment]
Having trouble testing this because im having another issur right now 

```
{
    "statusCode": 500,
    "body": "{\"message\":\"Failed\",\"error\":\"Error: Failed to launch the browser process!\\n\\n\\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\\n\\n    at onClose (/home/kay/kay/livestreamfailsclips/node_modules/puppeteer-core/src/node/BrowserRunner.ts:328:9)\\n    at Interface.<anonymous> (/home/kay/kay/livestreamfailsclips/node_modules/puppeteer-core/src/node/BrowserRunner.ts:314:16)\\n    at Interface.emit (node:events:525:35)\\n    at Interface.emit (node:domain:489:12)\\n    at Interface.close (node:internal/readline/interface:536:10)\\n    at Socket.onend (node:internal/readline/interface:262:10)\\n    at Socket.emit (node:events:525:35)\\n    at Socket.emit (node:domain:489:12)\\n    at endReadableNT (node:internal/streams/readable:1359:12)\\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\"}"
}
```

**Comment by sam09** [comment]
Hey so I created #53 

Setting `NODE_ENV` and `IS_LOCAL` together does not run the browser with the local installation and in headless mode.

Is it the desired behaviour or is it a bug?
If it is a bug, would you be accepting a bug fix?

**Comment by Sparticuz** [comment]
> Hey so I created #53
> 
> Setting `NODE_ENV` and `IS_LOCAL` together does not run the browser with the local installation and in headless mode.
> 
> Is it the desired behaviour or is it a bug? If it is a bug, would you be accepting a bug fix?

It's a bug, I remember something broke when I refactored puppeteer out of the package. I'll accept a pr. I'd really like to fix all the env variables. I don't see a need for all of them, headless should just be a required variable and the user should know to set it properly.

**Comment by Sparticuz** [comment]
What probably should happen is `executablePath` should run https://github.com/npm/node-which and return any pre-installed chromium binary, which should allow headful operation. In fact, I think that's what I had altered. Since we use headless.gn to compile chromium, I think it's actually missing the gui.
