### ISSUE TITLE
[BUG] Unable to Execute Binary File in Local Development

### ISSUE THREAD

**Issue by PickertJoe** [Sparticuz/chromium#42]
## Environment
* `chromium` Version: 109
* `puppeteer` / `puppeteer-core` Version: 19.5.2
* Node.js Version: 16
* Lambda / GCF Runtime: nodejs 16.x
* MacOS 11.7.2
* x64 Intel processor and running Lambda with x64 architecture

## Expected Behavior

The chromium binary should execute

## Current Behavior

```
{
    "errorMessage": "Failed to launch the browser process!\n/tmp/chromium: /tmp/chromium: cannot execute binary file\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
    "errorType": "Error",
    "stackTrace": [
        "Error: Failed to launch the browser process!",
        "/tmp/chromium: /tmp/chromium: cannot execute binary file",
        "",
        "",
        "TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md",
        "",
        "    at onClose (/path-hidden/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)",
        "    at Interface.<anonymous> (/path-hiddden/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)",
        "    at Interface.emit (node:events:525:35)",
        "    at Interface.emit (node:domain:489:12)",
        "    at Interface.close (node:readline:590:8)",
        "    at Socket.onend (node:readline:280:10)",
        "    at Socket.emit (node:events:525:35)",
        "    at Socket.emit (node:domain:489:12)",
        "    at endReadableNT (node:internal/streams/readable:1358:12)",
        "    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    ]
}
```

## Steps to Reproduce

1. Follow installation steps in documentation (installing @Sparticuz/chromium as a dev dependency)
2. export IS_LOCAL=true
3. Try running lambda function with serverless offline

Lambda function code example:

```js
import 'source-map-support/register';

import type { ValidatedEventAPIGatewayProxyEvent } from '@/utils/apiGateway';
import { middyfy } from '@/middleware';

import schema from './schema';

const chromium = require('@sparticuz/chromium');
const puppeteer = require('puppeteer-core');

const capture: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async (
  event,
) => {
  const { queryStringParameters } = event;
  if (
    !queryStringParameters ||
    !queryStringParameters.url ||
    !queryStringParameters.screen
  ) {
    return { statusCode: 403 };
  }

  const { url } = queryStringParameters;
  console.log(queryStringParameters);
  const [width, height] = queryStringParameters.screen.split(',');

  if (!width || !height) {
    return { statusCode: 403 };
  }

  console.log('About to launch the browser...');
  const execPath = await chromium.executablePath();
  console.log(execPath);
  console.log(process.version);
  console.log(process.env.IS_LOCAL);
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
  const browser = await puppeteer.launch({
    headless: true,
  });
  console.log('I launched the browser!!');

  const page = await browser.newPage();
  await page.setViewport({
    width: Number(width),
    height: Number(height),
  });

  await page.goto('https://example.com');
  console.log(`Page title ${await page.title()}`);
  const screenshot = await page.screenshot({
    path: 'screenshot.png',
    encoding: 'base64',
  });

  await browser.close();

  return {
    statusCode: 200,
    body: `<img src=”data:image/png;base64,${screenshot}”>`,
    headers: { 'Content-Type': 'text/html' },
  };
};

export const main = middyfy(capture);
```

The console logs confirm that my lambda is running is node 16 and that the chromium.exectubalePath() is pointing to /tmp/chromium.

The function blows up when I try to launch the browser:
`  const browser = await puppeteer.launch({`

When I open /tmp/chromium and attempt to execute the file, I also get
`zsh: exec format error: ./chromium`. This leads me to believe there may be an issue with the chromium binary file

**Comment by kaykhan** [comment]
Having the same issue, did you manage to find any workaround?

**Comment by PickertJoe** [comment]
@kaykhan I was not, unfortunately 😞 I ended up switching over to [playwright-aws-lambda](https://github.com/JupiterOne/playwright-aws-lambda) and have had much better luck! It worked right out of the box

**Comment by Sparticuz** [comment]
Does sls offline run a docker container similar to how aws sam does their testing? If so, you might need to make the binaries available to the container, whether that's making them production dependencies, or layers, etc..

You can also try the @sparticuz/chromium-min package and provide a location for the files.

If you don't need a newer version of chromium, playwright-aws-lamda looks extremely similar to chrome-aws-lambda. The main difference being that chromium is over two years old!

**Comment by kaykhan** [comment]
Just to clarify but this problem does not only just exists with `sls offline`. it also exists with `sls invoke local -f <function_name`

**Comment by Sparticuz** [comment]
If you specify the package as a production dependency does it work?

**Comment by PickertJoe** [comment]
@Sparticuz @kaykhan For further clarification to my posts above, `playwright-aws-lambda` worked fine locally using serverless offline but did not work when actually deployed. Probably to your point @Sparticuz that the binaries included in that package are super old.

Using this package as a production dependency, everything works perfectly in deployed environments! But I'm still seeing the same error described above in which my local environment seems unable to run the inflated executable file. Would you mind sharing where you're sourcing these binaries @Sparticuz? I don't know if there are any OS-related gotchas here, but my hunch is that there might be. I'm also going to try running my project on my Linux machine this weekend to see if this local dev issue is still present there

**Comment by kaykhan** [comment]
> If you specify the package as a production dependency does it work?

Ive been installing via `npm install <package>` rather than a dev dependency. Becuase ive been attempting to develop locally. And it does not work like this

**Comment by Sparticuz** [comment]
> Would you mind sharing where you're sourcing these binaries @Sparticuz?

https://github.com/Sparticuz/chromium/tree/master/_/ansible

**Comment by kaykhan** [comment]
Im still experiecing this problem locally running `sls invoke local -f <function_name>` 

**package.json**
```
  "dependencies": {
    "@sparticuz/chromium": "^110.0.0",
    "puppeteer-core": "19.6.0",
    "puppeteer-extra": "^3.3.4",
    "puppeteer-extra-plugin-stealth": "^2.11.1",
    ....
  },
  ```

**code**
```
const puppeteer = require("puppeteer-extra");
const chromium = require("@sparticuz/chromium");

const StealthPlugin = require("puppeteer-extra-plugin-stealth")();
StealthPlugin.enabledEvasions.delete("iframe.contentWindow");
StealthPlugin.enabledEvasions.delete("navigator.plugins");
puppeteer.use(StealthPlugin);

browser = await puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath(),
        //headless: chromium.headless,
        ignoreHTTPSErrors: true,
        headless: false,
});
```

node v18

is there anything obvious you can see im doing wrong?
