### ISSUE TITLE
[REQUEST] Explicit migration instructions from chrome-aws-lambda

### ISSUE THREAD

**Issue by maxmoore14** [Sparticuz/chromium#45]
I have been using https://github.com/alixaxel/chrome-aws-lambda as a Lambda Layer for a couple of years now. I would like to migrate to this package and upgrade to nodejs 18.x.

Lambda layer deployment and usage is still quite opaque to me though, so I am looking for detailed instructions to get migrated with both chromium and puppeteer-core.

This request is specifically to update this section of the README: https://github.com/Sparticuz/chromium#aws-lambda-layer to include instructions for:

1. creating the package correctly on Windows (though the layer artifact works to skip this step)
2. creating an equivalent package on Windows for puppeteer-core

I have been able to successfully use the artifact and load chromium as a layer for my lambda function, but I cannot seem to find anything on creating the puppeteer-core layer or anything pre-built to download.

**Comment by 5neaX** [comment]
Hey @maxmoore14 don't get excited I'm just a noob. Atleast you've got a working puppeteer-core AWS chromium layer working already though right ? I've spent about 2 weeks just trying to get to that step. Started at the noob direct zip and upload approach, then the cdk-aws approach, and I can't for the life of me figure it out, I guess ill learn how the layer approach works and try my best. Sorry for unhelpful comment, but got any tutorials or such you can point me too given I'm a noob, I've been exhausting most of the online recourses and they're all out of date, I'd use node12 If I have to 🤣

**Comment by 5neaX** [comment]
@maxmoore14  I did find this, it's about the only recent tutorial I could find https://www.cloudtechsimplified.com/puppeteer-aws-lambda/

It's using the cdk-aws method , it's a bit breif on the complex parts though ? might be a walk in the park for you

**Comment by maxmoore14** [comment]
@5neaX That last blog post is interesting, but I'm not using the CDK they reference unfortunately. You are correct - it glosses over the details I'm looking for.

If it helps you, I'm still successfully able to use the older package for now: https://github.com/alixaxel/chrome-aws-lambda

- I downloaded the zip artifact
- I used the AWS Console to upload it to S3
- I used the AWS Console to create a Lambda Layer from the zip on S3
- I configured my Lambda function to use the Layer and Node.js 14.x
- The following is my index.js code:

```
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
    let browser;
    try {
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
            ignoreHTTPSErrors: true,
        });
		// TODO - use the browser
        return callback(null, 'success');
    } catch (err) {
        return callback(err);
    } finally {
        if (browser) {
            console.log('Closing browser.');
            await browser.close();
        }
    }
};
```

My issue is that I want to migrate to Node.js 18.x. I'm dangerous enough to convert my code to an ES6 module, but I'm lost on how I would go about creating the Layer zip file for puppeteer-core. "chrome-aws-lambda" had puppeteer included already while this new version intentionally excludes it for maintainability. All of the docs/blogs I have found expect access to a local Linux environment and gloss over node/npm basics. I'm generally a C# developer, so I only have Windows machines. I'd be very happy to build this all on Linux via CodeBuild, but again I'd be searching for help with the right instructions for my buildspec.yaml.

Hopefully the above helps you a little though.

**Comment by Sparticuz** [comment]
@maxmoore14  https://github.com/Sparticuz/chromium#migration-from-chrome-aws-lambda is the migration guide

For puppeteer-core, just add it as a dependency, you shouldn't need to make it a layer because it's small enough to be bundled.

Then for the chromium layer, you can download them [here](https://github.com/Sparticuz/chromium/releases)

**Comment by Sparticuz** [comment]
@maxmoore14 Also, you don't need to migrate to ESM for Node 18, it supports CJS just fine

**Comment by maxmoore14** [comment]
@Sparticuz Thanks for the note on CJS vs. ESM - I wasn't aware of that.

I was able to download and create the chromium layer from your build, but following the migration guide, this line is causing me the issue:

const puppeteer = require("puppeteer-core");

Lambda does not seem to be able to find the reference. Are you saying it is included with the Lambda node runtime? I had assumed I needed to include the code files somewhere.

**Comment by maxmoore14** [comment]
Not sure if this will help anyone else... I was able to get this working by altering my buildspec and installing puppeteer in the deployment process. Since I have CodeBuild configured to run on Linux:

I changed this:

- cd to directory with my index.js file
- zip HtmlFileToPdfFileNode.zip index.js

to this:

- cd to directory with my index.js file
- npm install puppeteer-core@19.6.3
- zip -r HtmlFileToPdfFileNode.zip .

**Comment by 5neaX** [comment]
@maxmoore14 what did you put in your chromium.executablePath(),? or do you just leave it blank? i think i did what youve done? I added a layer and connected it to the buvket that contaoned my chromium zip in s3. The layer is connected to my code (index.s function). using node14, 17 18 still get the failed to launch browser? am I supposed to configure something to point to the layer ?

**Comment by maxmoore14** [comment]
When you open the AWS Console, go to Lambda, then open the detail view for your particular function. On the "Code" tab, scroll all the way to the bottom. You should see an option to add your Layer there. This can also be done through the CLI of course.
