### ISSUE TITLE
[REQUEST] Nullish Coalescing Operator Error

### ISSUE THREAD

**Issue by raggya** [Sparticuz/chromium#46]
## Environment
* `chromium` Version: 109.0.6
* `puppeteer` / `puppeteer-core` Version: 10.4.0
* Node.js Version:  14.19.2

## Expected Behavior

Hi @Sparticuz,

I'm a little noob to the world of typescript and I have been working on trying to use the package in one of my existing projects.
When I build the code I get the below error.
![image](https://user-images.githubusercontent.com/3677522/216641558-7992142e-0ce3-4531-9f94-3cc1bfe72cb8.png)
The app is using webpack 4, typescript 4.5.4 and ts-loader: 8.3.0

I tried the babel plugin @babel/plugin-proposal-nullish-coalescing-operator but it didn't help either.
Could you please let me know what can be done.

**Comment by Sparticuz** [comment]
Very odd, I'm targeting node14 using @tsconfig/bases. Is there something in webpack or ts-loader that isn't able to use es2020?

Regardless, node14 is set to be end-of-life very soon and I will probably deprecate it accordingly. (30 Apr 2023)
