### ISSUE TITLE
[REQUEST] How to troubleshoot errors?

### ISSUE THREAD

**Issue by JobaDiniz** [Sparticuz/chromium#50]
## What would you like to have implemented?

Document best practices to troubleshoot errors since it's impossible to see the screens. I tried to use `sam local invoke` but that runs within a docker container and I get the same error as running in lambda.

Is there a way that we can test this outside of lambda maybe? What would be the best practices?

```
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Jg: Timeout 30000ms exceeded while waiting for event \"request\"\n=========================== logs ===========================\nwaiting for request \"https://some-http-request-page-make…\"\
```

**Code**
```
const pageRequestPromise = page.waitForRequest('some-http-request-page-make');
        await page.getByPlaceholder('Digite sua conta').fill(request.account);
        await page.getByRole('button', { name: 'Avançar' }).click();
        const pageRequest = await pageRequestPromise;
```

**Comment by milindsingh** [comment]
@JobaDiniz Checkout https://adapttive.com/blog/serverless-scraping#how-to-debug
