### ISSUE TITLE
[QUESTION] Can the binaries be used for dotnet?

### ISSUE THREAD

**Issue by JobaDiniz** [Sparticuz/chromium#51]
This is more of a newbie question, but I'm using playwright for dotnet and lambda functions with dotnet. Can I use the contents of  [bin](https://github.com/Sparticuz/chromium/tree/master/bin) folder with playwright + dotnet?

The `bin` folder is just how aws lambda will run chrome, right? If I point the executable to that folder, then it doesn't matter whether I'm running dotnet or nodejs. Am I right or completely wrong?

```c#
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
{
     Headless = false,
     ExecutablePath = "[the path]"
});
```

**Comment by Sparticuz** [comment]
You'll need to extract the brotli and tar files first, but it should work fine with anything after that's done

https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/

**Comment by JobaDiniz** [comment]
Okay.
Does this library extracts on-demand? Isn't this impacting performance of lambdas? Does every request to lambda extracts the content or if I use this package as layer it's extracted automatically by lambda?

**Comment by Podginator** [comment]
Saw this - and despite it being from... 2+ years ago.. Thought I'd at least post this here for anyone else that might be looking. 

https://github.com/Podginator/lambda-chromium-playwright-CSharp

I used the bin from here to do this, and got it working with Lambda.

@Sparticuz  If there's a way to include this or a PR to make to point people towards it - if you think that'd be helpful - let me know.

**Comment by Sparticuz** [comment]
Thanks, added a FAQ explaining how to use with other languages along with a link to @Podginator's project.
