### ISSUE TITLE
[BUG] Unable to run in headless mode using a Local binary

### ISSUE THREAD

**Issue by sam09** [Sparticuz/chromium#53]
## Environment
* `chromium` Version: 106.0.2
* `puppeteer-core` Version: 19.0.0
* Node.js Version: 16.x
* Lambda / GCF Runtime: 

## Expected Behavior
The following code snippet does not run my browser in headless mode, with the local binary. The env variables `NODE_ENV` is set to "test" and `IS_LOCAL` is set to `true`

## Current Behavior

The browser does not run in headless mode

## Steps to Reproduce

```js
const chromium = require('chromium');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

## Possible Solution

[Here](https://github.com/Sparticuz/chromium/blob/083fd747ffb381b1e034b1dd93347dd420a7a77f/source/index.ts#L229) is the code snippet that I think causes this behaviour.
IMO the order of comparisons should be reversed.

If this expected behaviour, maybe it can be made more clear in the README.

PS: Thanks for the work you put in

**Comment by Sparticuz** [comment]
dupe #38
