### ISSUE TITLE
[BUG] No redirect following during downloading brotli pack

### ISSUE THREAD

**Issue by zumm** [Sparticuz/chromium#56]
## Environment
-
## Expected Behavior
Follow redirects and throw meaningful error for other http codes.

## Current Behavior
`executablePath` throws "The input directory "/tmp/chromium-pack" does not exist." if brotli pack url has redirects (or return other http code that isn't 200).

## Steps to Reproduce
-
## Possible Solution
-

**Comment by Sparticuz** [comment]
Thank you! I was writing some examples today and couldn't figure out why it was failing! I'll look at this tomorrow
