### ISSUE TITLE
[BUG] spawn Unknown system error -8

### ISSUE THREAD

**Issue by jasonlew** [Sparticuz/chromium#63]
## Environment
* `chromium` Version: chromium-min 110.0.1
* `puppeteer` / `puppeteer-core` Version: puppeteer-core 19.6.3
* Node.js Version: 18.14.1
* Lambda / GCF Runtime: running locally first

## Expected Behavior

I tried to run the code [here](https://github.com/Sparticuz/chromium/tree/master/examples/remote-min-binary).

## Current Behavior

```
Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Module.spawn (node:child_process:757:9)
    at BrowserRunner.start (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/BrowserRunner.js:91:34)
    at ChromeLauncher.launch (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:68:16)
```

## Steps to Reproduce

See above.

**Comment by jasonlew** [comment]
I downgraded to Node 16.19.1, but now I'm getting:

```
Error: Failed to launch the browser process!
/var/folders/_k/pn98_hgn4cx_y2hw173_g1xw0000gn/T/chromium: /var/folders/_k/pn98_hgn4cx_y2hw173_g1xw0000gn/T/chromium: cannot execute binary file
```

**Comment by Sparticuz** [comment]
does the file download to `/tmp/chromium-pack`? What architecture is your cpu, this will only work on x86-64 processors.

**Comment by jasonlew** [comment]
I'm running a 2.4 GHz 8-Core Intel Core i9 on Mac. Is it because it won't work on Mac?

Also, is it supposed to work on Node 18 or only up to Node 16?

**Comment by Sparticuz** [comment]
It should support 16 and 18, not sure about 14 since it's EOL in a few weeks. It's compiled specifically for aws lambda, but I don't see any reason why it shouldn't work on the Mac though.

**Comment by Kal-Toh** [comment]
I'm having a similar error. I'm running this on Netlify dev on a m1 Mac to be pushed as a server less function on Netlify. 

```js 
const puppeteer = require('puppeteer-core');
const chromium = require('@sparticuz/chromium');
exports.handler = async function (event, context) {
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST',
      },
      body: '',
    };
  }

  const browser = await puppeteer.launch({
    args: chromium.args,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });
  ```
Returns me the error of:
`Error - spawn Unknown system error -8`
```ChildProcess.spawn (node:internal/child_process:420:11)
Object.spawn (node:child_process:757:9)
BrowserRunner.start (/Users/xyz/1.5/Server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:120:34)
ChromeLauncher.launch (/Users/xyz/1.5/Server/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:16)
async exports.handler (/Users/xyz/1.5/Server/functions/quote.js:20:19)

**Comment by rfoel** [comment]
Getting this error on mac M1 too. When I deploy to a lambda it works using this executablePath:

```
      executablePath: await chromium.executablePath(
        process.env.AWS_EXECUTION_ENV
          ? '/opt/nodejs/node_modules/@sparticuz/chromium/bin'
          : undefined,
      ),
```

**Comment by Kal-Toh** [comment]
Yeah, the issue for me was that it wasn't compatible with my systems architecture, thus wouldn't work on a local environment. It functions as expected when deployed. 

Best thing to do is code>deploy>test>code>deploy>test etc.

**Comment by donald-lendit** [comment]
I found a slightly improved method from the response of @rfoel. 
I thought the problem was simply to run Chromium in a local development environment, so I tried branching only executablePath. 

It's a bit cumbersome, but it works well in both AWS Lambda and local development environments.

1. Install Chromium with brew . [Reference link](https://www.reddit.com/r/MacOS/comments/q9d772/homebrew_chromium_is_damaged_and_cant_be_openend/)
   You can use no-quarantine flag at this point to prevent Chromium from warning you that it's corrupted.
`brew install chromium --no-quarantine`

2. Branch the executablePath.
```
const chromium = require('@sparticuz/chromium')
const puppeteer = require('puppeteer-core')

let browser = null

module.exports = async function () {
  const executablePath = process.env.AWS_EXECUTION_ENV
    ? await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin')
    : '/Applications/Chromium.app/Contents/MacOS/Chromium'
  if (browser === null) {
    browser = await puppeteer.launch({
      args: [...chromium.args, '--font-render-hinting=none'],
      executablePath,
      headless: true, // Generating a pdf is currently only supported in Chrome headless.
    })
  }
  return browser
}

```

Hope this helps.

**Comment by bhaktatejas922** [comment]
not working for me either on m1 mac

**Comment by Sparticuz** [comment]
> ```js
> executablePath: process.env.AWS_EXECUTION_ENV
>         ? await chromium.executablePath(
>             '/opt/nodejs/node_modules/@sparticuz/chromium/bin',
>           )
>         : playwright.chromium.executablePath(),
> ```

Yes, this is the correct way to handle arm at this point. You are saying if I'm running in AWS, use this package, otherwise, use playwright's version of chromium. I'm going to document this and close the multiple issues about running on ARM and running Headfully. Thanks for the insight.

**Comment by felipeclopes** [comment]
> does the file download to `/tmp/chromium-pack`? What architecture is your cpu, this will only work on x86-64 processors.

When running `serverless invoke local --function <name>` the standard code doesn't work on x86-64 Mac OS.

```
const browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
```

Do I need to use playwright to execute locally even on x86 architectures?

**Comment by bhaktatejas922** [comment]
you can do a 
` arch -x86_64 zsh `

in your terminal prior to running and it should work. You'll need to have the x86 packages installed prior to. You can do it by running this for example

`# Puppeteer or Playwright is a production dependency
npm install --arch=x86 --save puppeteer-core@18.0.5 

# @sparticuz/chromium can be a DEV dependency IF YOU ARE USING A LAYER, if you are not using a layer, use as a production dependency!
npm install --arch=x86 --save @sparticuz/chromium@106 `

**Comment by andredezzy** [comment]
Any news how about to execute locally even on M1/M2?

**Comment by andredezzy** [comment]
```js
import chromium from '@sparticuz/chromium-min';
import { executablePath } from 'puppeteer';
import * as puppeteer from 'puppeteer-core';

 browser = await puppeteer.launch(
      process.env.NODE_ENV === 'production'
        ? {
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath(
              'https://drive.google.com/uc?id=1Sw60gty75maoAr2fsIcu-CDJZ5O8RHrm&export=download',
            ),
            headless: chromium.headless,
            ignoreHTTPSErrors: true,
          }
        : {
            headless: false,
            executablePath: executablePath(),
          },
    );
```

For local development I did this and bow it's working.

**Comment by charleswklau** [comment]
@andredezzy 

I also use the same approach. It works for me as well. 

But have you experienced the PDF output difference? because sometimes I got an extra page, or some inconsistent styles in the remote/production side. It looks perfect in the local development.

**Comment by asadimohammad** [comment]
This happened for me because I was on the new macOS "Apple Silicon" in the terminal Apple will not prompt you to install Rosetta which is required for certain apps to run. Simply running `softwareupdate --install-rosetta` solved the issue for me.

More information about Rosetta here https://support.apple.com/en-gb/HT211861

**Comment by sedukhsergey** [comment]
Here there is a solution. https://github.com/puppeteer/puppeteer/issues/6634#issuecomment-755430921

On my side it works 

``` javascript
      if (process.env.STAGE === 'local') {
        browser = await puppeteer.launch({
          executablePath: '/Applications/Chromium.app/Contents/MacOS/Chromium',
          args: ['--no-sandbox', '--disable-setuid-sandbox'],
          headless: false,
        });
        console.log('browser', browser);
      }

      if (process.env.STAGE !== 'local') {
        browser = await puppeteerCore.launch({
          args: chromium.args,
          defaultViewport: chromium.defaultViewport,
          executablePath: await chromium.executablePath(),
          headless: chromium.headless,
          ignoreHTTPSErrors: true,
        });
      }
```
