### ISSUE TITLE
[REQUEST] Support Puppeteer Extra Plugins

### ISSUE THREAD

**Issue by rothnic** [Sparticuz/chromium#65]
## What would you like to have implemented?

I originally was using chrome-aws-lambda with puppeteer extra plugins to block requests. I ran into issues upgrading packages and deploying to serverless, and ended up leveraging this project instead. I was able to get this project working with puppeteer extra locally, but when deploying to aws via serverless, I get errors when triggering the endpoint.

It seems related to [this issue](https://github.com/berstend/puppeteer-extra/issues/730), but they were able to [work around it](https://github.com/berstend/puppeteer-extra/issues/730#issuecomment-1290243996) by using the executable path function from puppeteer. I tried taking this same approach with puppeteer-core instead, but I ended up with the error below. My understanding is that we don't want puppeteer as a production dependency, so it seems I either have to remove the puppeteer extra plugins or rework this into a docker container.

When running the function on aws, the error I receive is this:

```
ERROR Error: _projectRoot is undefined. Unable to create a BrowserFetcher. at resolveExecutablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:128:15) at ChromeLauncher.executablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:168:76) at PuppeteerNode.executablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Puppeteer.js:158:31) at module.exports.exports.handler (/var/task/extract.js:168:52) at Runtime.handler (/var/task/serverless_sdk/index.js:24:10716) at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)
```

## Why would it be useful?

So, anyone using this project can leverage puppeteer extra plugins.

**Comment by rothnic** [comment]
Playing around with this some more. I noticed that I hadn't yet upgraded `puppeteer-core`, so I did that. I'm on `19.7.2` of `puppeteer` (devDependencies) and `puppeteer-core` (dependencies). The odd thing is that with `puppeteer-extra` loaded the other error I get is `chromium.executablePath is not a function`.

When I debug the handler, it seems that `chromium.executablePath` is a promise object.

**Comment by milindsingh** [comment]
Yes @rothnic I am using it for serverless scraping. I have written an article and also made the code open source. Feel free to check it out.
https://adapttive.com/blog/serverless-scraping#how-to-debug 
https://github.com/openwishlist/preview

**Comment by rothnic** [comment]
> Yes @rothnic I am using it for serverless scraping. I have written an article and also made the code open source. Feel free to check it out. https://adapttive.com/blog/serverless-scraping#how-to-debug https://github.com/openwishlist/preview

Thanks, I ended up figuring out. I think I was referencing multiple examples that each didn't address my whole use case. Here is roughly how it is setup at the beginning of my handler.

```
const chromium = require("@sparticuz/chromium");

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const PuppeteerExtraPluginAdblocker = require('puppeteer-extra-plugin-adblocker');

const config = require('./config');
const schema = require('./schema');
const utils = require('./utils');

puppeteer.use(StealthPlugin());
puppeteer.use(PuppeteerExtraPluginAdblocker({
  blockTrackers: true,
  blockTrackersAndAnnoyances: true
}));

const localPath = config.LOCAL_CHROME_PATH;

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  event.isOffline = event.requestContext.domainName === 'offlineContext_domainName';

  // use headless when we aren't in offline mode
  chromium.headless = !event.isOffline;
  const executablePath = event.isOffline ? localPath : await chromium.executablePath;

  browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: executablePath,
    headless: chromium.headless,
  });

  // continue on with your code to leverage the browser
```

**Comment by iwaduarte** [comment]
Suppose anyone stumbles upon this error/issue/request you should consider 3 things:

1 - Puppeteer-extra is only a wrapper of the puppeteer which means it only adds extra sauce on top of it
2 - This package is the **browser** with less stuff therefore smaller
3 - Puppeteer is the puppeteer-core + browser. In our case, we only need a puppeteer-core. 

So the actual setup is:

```
npm install puppeteer-core
npm install puppeter-extra 
npm install @sparticuz/chromium 
```

Code:

cjs 

```
const chromium = require("@sparticuz/chromium");
const puppeteer = require('puppeteer-extra');

// whatever extra plugin you need
const StealthPlugin = require('puppeteer-extra-plugin-stealth');

const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });

```
esm

```
import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-extra";

// whatever extra plugin you need
import StealthPlugin from "puppeteer-extra-plugin-stealth";

// ...everything else remains the same

```


Note that although puppeteer-core wasn't imported it is used inside puppeteer-extra. 
Specifically this line https://github.com/berstend/puppeteer-extra/blob/39248f1f5deeb21b1e7eb6ae07b8ef73f1231ab9/packages/puppeteer-extra/src/index.ts#L528
