### ISSUE TITLE
[QUESTION] Difference between serverless-plugin-chrome vs @sparticuz/chromium

### ISSUE THREAD

**Issue by pratiksyngenta** [Sparticuz/chromium#7]
I am implementing a common html to pdf generation service for my application.
been through various resources such as

https://www.npmjs.com/package/chrome-aws-lambda
https://github.com/alixaxel/chrome-aws-lambda
https://www.npmjs.com/package/@sparticuz/chrome-aws-lambda
https://github.com/Sparticuz/chromium

and
https://github.com/adieuadieu/serverless-chrome/tree/master/packages/serverless-plugin
serverless-plugin-chrome

need a suggestion what is the difference 
serverless-plugin-chrome vs @sparticuz/chromium

https://github.com/adieuadieu/serverless-chrome/issues/177

**Comment by Sparticuz** [comment]
serverless-chrome is a serverless plugin, but only supports up to chromium 88

alixaxel's chrome-aws-lambda support overriding puppeteer's functions as well as some other hooks, but the last version only supports puppeteer 10.1, chromium 92

@sparticuz/chrome-aws-lambda was my fork of alixaxel's repo, and continues compiling chromium supporting up to puppeteer 17.1.3, chromium 106

@sparticuz/chromium is ONLY chromium, not bundling puppeteer, or the overrides and hooks. This package can be used with any nodejs system. Puppeteer/playwright/etc... I'm biased, but I would use this. It seems to be the only one being actively maintained, currently supports up to chromium 108.
