### ISSUE TITLE
50MB AWS Limit

### ISSUE THREAD

**Issue by wesbos** [Sparticuz/chromium#8]
Trying to switch over to this from chrome-aws-lamda, but now my host, Netlify, is giving my grief because it's 53mb, 3mb over the 50mb limit.

Did something change to make this go over 50mb?

**Comment by brunoargolo** [comment]
@wesbos I had the same issue recently, I guess the binary was already hovering around that limit so new version of it just crossed it. A simple solution is to package @sparticus/chromium as a lambda layer.

If you're using commonjs that should be straight forward, just follow sparticus instructions to make the zip package, if you use ESM modules you might need a workaround to import the lib: https://github.com/vibe/aws-esm-modules-layer-support

In my case I packaged only @sparticuz/chromium into the layer (not the whole node modules) so the **ln** command would look like this:

cd directory-with-function-code
ln -s /opt/nodejs/node_modules/@sparticuz/chromium node_modules/@sparticuz/chromium
zip --symlinks -r function.zip .

**Comment by Sparticuz** [comment]
It's been over 50 megs for a while. Research needs to be done on build flags to bring the size down, but yes, you should be able to get around it by deploying it as a layer, not sure how that works with Netlify though.

**Comment by wesbos** [comment]
Okay thanks a lot. Netlify doesnt support layers, so I will likely have to move to another host for my serverless functions.

Some more info on this, as I have talked to at least 20 people who have the same issue. We're all just reverting to Node 12 runtime, which will stop working March 2023

https://answers.netlify.com/t/netlify-function-with-puppeteer-breaks-if-i-make-any-changes/76924

**Comment by Sparticuz** [comment]
I've replied on the netlify post, but I'll add the same here.

Chromium uncompressed is 152 megs, and with brotli compression, I get it down to 51 megs. This is still over the limit in many places though.

One feature I've been looking for time to implement is having a remote location for the brotli file, so on first run, it would curl the brotli file and then extract it to /tmp/chromium.

**Comment by wesbos** [comment]
That would be super handy! Is it something I could do myself with the existing code? Or would need to be done at a library level?

**Comment by Sparticuz** [comment]
I guess you could implement this in existing code, but it should be done in the package. Basically, my thought is that [this function](https://github.com/Sparticuz/chromium/blob/7b58b551cf15640cec73701c3796e747ad8734f1/source/index.ts#L182) should take a path as an argument. If it's a local path, then it should extract and continue as normal, if it's a remote path, it should download the brotli file, then extract and continue as normal

**Comment by samkim** [comment]
> @Sparticuz is there a specific version that we know is well below that 50 MiB limit? That way I can use it for the time being until we figure out how to compress newer versions more aggressively?

We've had success with ~9.0.0 of both puppeteer-core and chrome-aws-lambda. (We had to go pretty far back so we used chrome-aws-lambda instead of Sparticuz/chromium). The package build itself was 48.8 MB compressed and uncompressed in a vercel build.

**Comment by amccloud** [comment]
Also stuck on node 12 because of this and oddly enough those lambda are starting to decay. With no changes on my side images grabbed from the chromium instance have all started to appear darker. I suspect this may have to do with Vercel deprecating node 12 recently.

I'd hate to stand up infra to deploy my own lambda layer but seems that Is required if you want modern chrome + lambda.  I don't think there are any modern versions of chrome that compress small enough to fit inside the 50mb limit. I've attempted other compression algorithms like zstd and brotli still yielded the best results.

**Comment by mfs-private** [comment]
@samkim / @amccloud I'm curious why you haven't used container images instead? They seem to much higher size limits

**Comment by wesbos** [comment]
Most of us are using Netlify Fucntions, or Vercel Functions and can't deploy a layer, or an image.

Cloudflare just announced Puppeteer inside Workers, so this might be a good solution if you are OK with changing vendors. Their wrangler workflow is really nice. 

https://blog.cloudflare.com/introducing-workers-browser-rendering-api/

**Comment by jwchang0206** [comment]
@amccloud I found this [gist](https://gist.github.com/kettanaito/56861aff96e6debc575d522dd03e5725#step-1-install-dependencies) and it seems to require Node v14.

**Comment by Sparticuz** [comment]
Perhaps I can try to build older versions of chromium and find out where the boundary was crossed, then publish that version of chromium.

**Comment by amccloud** [comment]
@jwchang0206 thanks for the tip! Even the node@14 version is ~1mb too large for me when paired with a ~1mb nextjs app. I could spin this out into its own app to just make it under the limit. I'm afraid the size issue will repeat when node@14 is deprecated and we are forced to upgrade puppeteer/chromium again.

> Perhaps I can try to build older versions of chromium and find out where the boundary was crossed, then publish that version of chromium.

@Sparticuz  For everything to fit with some spare room in my app, I have to use:
- **puppeteer@3.3.0, chromium@83.0.4103.0, node@12**: Works but has an odd issue with visual artifacts in canvas elements)
- **puppeteer@2.0.0, chromium@79.0.3942.0, node@12**: First version that is small and renders without artifacts)
- **puppeteer@14, chromium@103.0.5059.0, node@14**: Works in a standalone lambda without much room for api/app
- **puppeteer@16, chromium@???, node@16**: Too big for lambda


Would you be open to switching over to a stripped-down version of chromium like https://github.com/ungoogled-software/ungoogled-chromium? I wonder if there are features to strip out like video, audio, localization, etc., that could save an additional ~5mb after compression.

**Comment by alessbelli** [comment]
I remember the threshold being crossed around the 80-85 version mark (chrome 77 was below, IIRC 87 was slightly above). it's probably a losing game to try to do slower and slower compression to fit 1% more data from the newer chromium binaries.

**Comment by Sparticuz** [comment]
I've published [@sparticuz/chromium@92](https://www.npmjs.com/package/@sparticuz/chromium/v/92.0.0) as well as [@sparticuz/chromium@103](https://www.npmjs.com/package/@sparticuz/chromium/v/103.0.0). 103 is from my old package, @sparticuz/chrome-aws-lambda, 92 is from @alixaxel/chrome-aws-lambda.

Note: I pulled the binaries from the compiled packages, I did not recompile.
Note 2: I couldn't get opengl working on v92, but 92 looks like it's 49.5 megs, so it should fit in vercel.
Note 3: Remember, puppeteer requires a specific version of chromium, so 92 should be puppeteer 10.1.0, and 103 should be pinned to puppeteer 15.0.2

**Comment by amccloud** [comment]
@Sparticuz thanks for that. v103 is too big with:

> Error: The Serverless Function "api/vr/[roomId]" is 52.95mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size

v92 seems to fit and work for most cases. For some reason `canvas.getContext('webgl')` always returns null. It [looks like everything is enabled in chrome://gpu](https://imgur.com/4nVDdkw) which adds to the confusion.

**Comment by Sparticuz** [comment]
I couldn't get v92 working with opengl, I don't remember the settings I originally had that made this work on chrome-aws-lambda. If you get it working, send in a PR to https://github.com/Sparticuz/chromium/tree/chromium/92

As a whole, this issue will be fixed by #18 , help wanted

**Comment by Sparticuz** [comment]
I've published v109.0.1 which supports a custom location for the chromium.br and associated files. This will fix this issue for some of you. In order to fully fix this issue, we need to support remote locations for the brotli files.

**Comment by Sparticuz** [comment]
HUGE Update for this bug!

v109.0.6 has been published with now lets you use a remote location for the brotli files (now a .tar pack). Super thanks to @aqaurius6666 for the code!!

**Comment by Sparticuz** [comment]
Also, specifically for this bug. I've published https://www.npmjs.com/package/@sparticuz/chromium-min which is identical to the @sparticuz/chromium package, but does not include the binaries. 30kb!
