### ISSUE TITLE
[BUG] Version 112.0.2 freezes on puppeteer.launch

### ISSUE THREAD

**Issue by Squeezemind** [Sparticuz/chromium#94]
## Environment
* `chromium` Version: 112.0.2
* `puppeteer` / `puppeteer-core` Version: 19.11.1
* Node.js Version: 18.x
* Lambda / GCF Runtime: x86_64

## Current Behavior

The code after _await puppeteer.launch_ is never executed due to timeout error:

Response
{
  "errorMessage": "2023-04-27T14:36:22.894Z 67769363-c82e-4cf6-be7e-f15e3391e4eb Task timed out after 30.01 seconds"
}

Dependencies were loaded using lambda layer

## Steps to Reproduce

**Freezes:**

```js
const puppeteer = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");

exports.handler = async (event, context, callback) => {  
  
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });
  
  return callback(null, JSON.stringify("Hello"));

};
```

**Don't freezes:**

```js
const puppeteer = require("puppeteer-core");
const chromium = require("@sparticuz/chromium");

exports.handler = async (event, context, callback) => {  

  return callback(null, JSON.stringify("Hello"));

  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });

};
```

https://user-images.githubusercontent.com/19249394/234901873-3a1c3b9b-c58e-40c0-9045-63b9dab4efdc.mp4

**Comment by Squeezemind** [comment]
My mistake. It works well using Chromium 112.0.2 and Puppeteer v19.8.0

**Comment by Loufi1** [comment]
> My mistake. It works well using Chromium 112.0.2 and Puppeteer v19.8.0

I'm facing the same issue how did you fix it ?

**Comment by Squeezemind** [comment]
> > My mistake. It works well using Chromium 112.0.2 and Puppeteer v19.8.0
> 
> I'm facing the same issue how did you fix it ?

Just use the correct version of Chromium and Puppeteer as reported [here](https://pptr.dev/chromium-support).

I created a lambda layer with Chromium 112.0.2 and Puppeteer v19.8.0 (instead of 19.11.1). Then I added it to my lambda function using the AWS lambda interface and all worked well.

**Comment by DurandA** [comment]
I'm facing the same issue. I tried with Chromium 112.0.2 and Puppeteer v19.8.0 as suggested. However, I did not use a lambda layer but I zipped the dependencies as [documented here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html). Is there anything wrong with this approach?
